export const dynamic = "force-dynamic";
export const revalidate = 0;

import { createServerSupabase } from "@/lib/supabase-server";
import { unstable_cache } from "next/cache";
import { notFound, permanentRedirect } from "next/navigation";
import Link from "next/link";
import ArticleContent from "@/components/ArticleContent";
import EvidenceHighlights from "@/components/EvidenceHighlights";
import LicensedNewsArticle from "@/components/LicensedNewsArticle";
import ArticleViewTracker from "@/components/ArticleViewTracker";
import { resolveDisplayImage, isVerifiedReusableArticleImage } from "@/lib/news/categoryImage";
import { SITE_URL, absoluteSiteUrl } from "@/lib/siteUrl";
import { isPublicNewsArticle } from "@/lib/articleStreams";
import { parseNewsPresentation } from "@/lib/news/newsPresentation";
import { normalizedPublicCategory, repairedNewsTitle } from "@/lib/publicArticleRepair";

function stripHtml(value = "") { return String(value || "").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim(); }
function formatDate(value) { if (!value) return ""; return new Date(value).toLocaleDateString("en-IN", { timeZone: "Asia/Kolkata", day: "numeric", month: "long", year: "numeric" }); }
function escapeRegExp(value = "") { return String(value).replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }
function cleanNewsSection(value = "", labels = []) { let text=String(value||"").trim();if(!text)return"";for(let pass=0;pass<3;pass+=1){let changed=false;for(const label of labels){const safe=escapeRegExp(label);const patterns=[new RegExp(`^#{1,6}\\s+${safe}\\s*:?[\\t ]*(?:\\r?\\n)+`,"i"),new RegExp(`^\\*\\*${safe}\\*\\*\\s*:?[\\t ]*(?:\\r?\\n)+`,"i"),new RegExp(`^${safe}\\s*:?[\\t ]*(?:\\r?\\n)+`,"i")];for(const pattern of patterns){const next=text.replace(pattern,"").trim();if(next!==text){text=next;changed=true;}}}if(!changed)break;}return text; }
function cleanManualNewsBody(value="",title=""){let text=String(value||"").replace(/\[\[NEWS_(?:START|END)\]\]/gi,"").replace(/^\s*NEWS_(?:TITLE|SCOPE|SECTION|DATE|STYLE|IMAGE)\s*:\s*.*$/gim,"").replace(/^\s*PART\s+\d+\s*\|\s*NEWS\s+\d+\s*[-–]\s*\d+.*$/gim,"").replace(/^\s*CURRENTPULSE\s+NEWS\s*$/gim,"").trim();if(title&&text.toLowerCase().startsWith(title.toLowerCase()))text=text.slice(title.length).replace(/^\s*[-:|–—]+\s*/,"").trim();return text;}

const NEWS_LOCATIONS=[
  ["BISHKEK","Bishkek","Kyrgyzstan",42.8746,74.5698],["KYRGYZSTAN","Bishkek","Kyrgyzstan",42.8746,74.5698],["KATHMANDU","Kathmandu","Nepal",27.7172,85.3240],["KYIV","Kyiv","Ukraine",50.4501,30.5234],["MOSCOW","Moscow","Russia",55.7558,37.6173],["PATNA","Patna","India",25.5941,85.1376],["RANCHI","Ranchi","India",23.3441,85.3096],["NEW DELHI","New Delhi","India",28.6139,77.2090],["DELHI","Delhi","India",28.7041,77.1025],["MUMBAI","Mumbai","India",19.0760,72.8777],["BEIJING","Beijing","China",39.9042,116.4074],["WASHINGTON","Washington, D.C.","United States",38.9072,-77.0369],["BRUSSELS","Brussels","Belgium",50.8503,4.3517]
];
const COUNTRY_ATLAS={
  Kyrgyzstan:{region:"Central Asia · landlocked",neighbors:["Kazakhstan","China","Tajikistan","Uzbekistan"],features:["Tien Shan","Issyk-Kul","Pamir-Alay"]},
  Nepal:{region:"South Asia · Himalayan state",neighbors:["India","China"],features:["Himalaya","Terai","Koshi-Gandaki-Karnali"]},
  Ukraine:{region:"Eastern Europe · Black Sea region",neighbors:["Poland","Slovakia","Hungary","Romania","Moldova","Russia","Belarus"],features:["Dnieper","Carpathians","Black Sea"]},
  Russia:{region:"Eurasia",neighbors:["Norway","Finland","Baltic states","Belarus","Ukraine","Kazakhstan","China","Mongolia"],features:["Ural Mountains","Volga","Caspian Sea"]},
  China:{region:"East Asia",neighbors:["India","Russia","Mongolia","Kazakhstan","Pakistan","Nepal"],features:["Tibetan Plateau","Yangtze","Yellow River"]},
  India:{region:"South Asia",neighbors:["Pakistan","China","Nepal","Bhutan","Bangladesh","Myanmar"],features:["Himalaya","Ganga system","Indian Ocean"]},
  Belgium:{region:"Western Europe",neighbors:["France","Germany","Netherlands","Luxembourg"],features:["North Sea","Meuse","Scheldt"]},
  "United States":{region:"North America",neighbors:["Canada","Mexico"],features:["Rocky Mountains","Mississippi","Atlantic & Pacific"]}
};
function primaryNewsLocation(text=""){const upper=String(text||"").toUpperCase();for(const[token,city,country,lat,lon]of NEWS_LOCATIONS){if(upper.includes(token))return{city,country,lat,lon,label:`${city}, ${country}`};}return null;}
function backgroundPosition(location){const x=Math.max(0,Math.min(100,(location.lon+180)/360*100));const y=Math.max(0,Math.min(100,(90-location.lat)/180*100));return `${x}% ${y}%`;}
function NewsAtlasMap({location}){if(!location)return null;const atlas=COUNTRY_ATLAS[location.country]||{region:"Location in news",neighbors:[],features:[]};const political=location.country==="India"?"/maps/india-location-map.svg":"/maps/world-location-map.svg";const physical=location.country==="India"?"/maps/india-relief-location-map.jpg":"/maps/world-physical-map.jpg";const pos=backgroundPosition(location);return <aside className="news-atlas-map"><div className="news-atlas-head"><div><strong>Location in News</strong><h3>{location.country}</h3></div><span>{location.city} · {atlas.region}</span></div><div className="news-atlas-grid"><div className="news-atlas-panel news-atlas-world" style={{backgroundImage:`url(${political})`}}><b>World locator</b><i style={{left:`${(location.lon+180)/360*100}%`,top:`${(90-location.lat)/180*100}%`}}></i></div><div className="news-atlas-panel news-atlas-region" style={{backgroundImage:`url(${political})`,backgroundPosition:pos}}><b>Political context</b><span>{atlas.neighbors.slice(0,5).join(" · ")||location.country}</span></div><div className="news-atlas-panel news-atlas-region" style={{backgroundImage:`url(${physical})`,backgroundPosition:pos}}><b>Physical geography</b><span>{atlas.features.slice(0,4).join(" · ")||atlas.region}</span></div></div></aside>}

const getArticle = unstable_cache(async (slug) => {
  const supabase = createServerSupabase();
  const { data } = await supabase.from("articles")
    .select("*,article_sources(id,source_kind,source_name,source_title,source_url,source_published_at,source_key)")
    .eq("slug", slug).eq("status", "published").maybeSingle();
  return data && isPublicNewsArticle(data) ? data : null;
}, ["currentpulse-news-detail-v5"], { revalidate: 60, tags: ["currentpulse-articles", "currentpulse-news"] });

export async function generateMetadata({ params }) {
  const { slug } = await params; const article = await getArticle(slug);
  if (!article) return { title: "News Not Found | CurrentPulse AI", robots: { index: false, follow: false } };
  const image=resolveDisplayImage(article);const newsPresentation=parseNewsPresentation(article.content);const title=newsPresentation?.title||repairedNewsTitle(article);const licensedConversation=Array.isArray(article.quality_flags)&&article.quality_flags.includes("licensed_republish_the_conversation");const originalConversationUrl=licensedConversation?article.article_sources?.find((source)=>source.source_kind==="news"&&source.source_name==="The Conversation")?.source_url:"";const description=stripHtml(newsPresentation?.lead||article.seo_description||article.why_news||article.content).slice(0,160);
  return { title, description, alternates:{canonical:licensedConversation&&originalConversationUrl?originalConversationUrl:`${SITE_URL}/news/${slug}`}, openGraph:{title,description,url:`${SITE_URL}/news/${slug}`,type:"article",publishedTime:article.created_at,modifiedTime:article.updated_at||article.created_at,...(image?{images:[{url:absoluteSiteUrl(image),width:1200,height:630}]}:{})}, twitter:{card:image?"summary_large_image":"summary",title,description,...(image?{images:[absoluteSiteUrl(image)]}:{})}, robots:licensedConversation?{index:false,follow:true}:{index:true,follow:true} };
}

export default async function NewsArticlePage({ params }) {
  const { slug }=await params;const article=await getArticle(slug);if(!article)notFound();const sources=article.article_sources||[];const newsSources=sources.filter((source)=>source.source_kind==="news");const hasCoachingSource=sources.some((source)=>source.source_kind==="coaching");if(!newsSources.length&&hasCoachingSource)permanentRedirect(`/current-affairs/${slug}`);
  const newsPresentation=parseNewsPresentation(article.content);const title=newsPresentation?.title||repairedNewsTitle(article);const newsLead=cleanNewsSection(newsPresentation?.lead||article.why_news,["What happened","Why in News","The development"]);const category=normalizedPublicCategory(article.category,`${title} ${newsLead||article.why_news||article.content||""}`);const newsFacts=cleanNewsSection(newsPresentation?.keyFacts||article.data_examples,["Key facts","At a glance","Data, Reports, Cases & Examples"]);const newsContext=cleanNewsSection(newsPresentation?.context||article.static_foundation,["Context","Background","Static Foundation"]);const newsWhyItMatters=cleanNewsSection(newsPresentation?.whyItMatters||article.india_relevance,["Why it matters","Significance","India relevance"]);const fullManualBody=!newsPresentation?cleanManualNewsBody(article.content||article.why_news,title):"";const mapLocation=primaryNewsLocation(`${fullManualBody} ${newsLead} ${newsContext} ${title}`);const image=resolveDisplayImage(article);const verifiedReusableImage=isVerifiedReusableArticleImage(article);const canonical=`${SITE_URL}/news/${slug}`;const licensedConversation=Array.isArray(article.quality_flags)&&article.quality_flags.includes("licensed_republish_the_conversation");if(licensedConversation)return <LicensedNewsArticle article={article} sources={sources}/>;
  const structuredData={"@context":"https://schema.org","@type":"NewsArticle",headline:title,description:stripHtml(newsLead||fullManualBody).slice(0,300),datePublished:article.created_at,dateModified:article.updated_at||article.created_at,mainEntityOfPage:canonical,...(image?{image:[absoluteSiteUrl(image)]}:{}),author:{"@type":"Organization",name:"CurrentPulse Newsroom",url:SITE_URL},publisher:{"@type":"Organization",name:"CurrentPulse AI",url:SITE_URL},citation:newsSources.map((source)=>source.source_url).filter(Boolean)};
  return <><ArticleViewTracker slug={slug}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData)}}/><main className="news-article-page min-h-screen"><article className="news-article-shell"><nav className="news-article-breadcrumb"><Link href="/">Home</Link> / <Link href="/news">News</Link> / <span>{category}</span></nav><p className="news-article-category">{category||"Latest News"}</p><h1>{title}</h1><div className="news-article-byline"><span>CurrentPulse Newsroom</span><time>Published {formatDate(article.created_at)}</time>{article.updated_at!==article.created_at&&<time>Updated {formatDate(article.updated_at)}</time>}</div>
  {image&&<figure className="news-article-figure news-article-figure--compact"><img src={image} alt={article.image_alt||title}/>{verifiedReusableImage&&article.image_caption&&<figcaption>{article.image_caption}</figcaption>}</figure>}
  {fullManualBody?<section className="news-article-section news-full-story"><ArticleContent content={fullManualBody}/></section>:<><section className="news-article-lead"><div className="news-section-kicker">The development</div><h2>What happened</h2><ArticleContent content={newsLead}/></section>{newsFacts&&<section className="news-article-section news-article-facts"><div className="news-section-kicker">At a glance</div><h2>Key facts</h2><EvidenceHighlights content={newsFacts} limit={5}/></section>}{newsContext&&<section className="news-article-section"><div className="news-section-kicker">Background</div><h2>Context</h2><ArticleContent content={newsContext}/></section>}{newsWhyItMatters&&<section className="news-article-section news-article-why"><div className="news-section-kicker">Significance</div><h2>Why it matters</h2><ArticleContent content={newsWhyItMatters}/></section>}</>}
  <NewsAtlasMap location={mapLocation}/>
  {sources.length>0&&<section className="news-source-box"><h2>Sources</h2><ul>{sources.map((source)=><li key={source.id}><a href={source.source_url} target="_blank" rel="noopener noreferrer"><strong>{source.source_name}</strong>{source.source_title?` — ${source.source_title}`:""}</a></li>)}</ul></section>}
  <div className="news-article-footer"><Link href="/news">← Back to latest news</Link></div></article></main><style>{`.news-article-figure--compact{max-width:340px;margin:22px 0}.news-article-figure--compact img{width:100%;max-height:210px;object-fit:cover;border-radius:14px}.news-full-story{font-size:1.02rem;line-height:1.8}.news-atlas-map{margin:30px 0;max-width:720px;border:1px solid rgba(148,163,184,.22);border-radius:16px;overflow:hidden;background:#0f172a}.news-atlas-head{display:flex;align-items:flex-end;justify-content:space-between;gap:12px;padding:12px 14px;border-bottom:1px solid rgba(148,163,184,.16)}.news-atlas-head strong{display:block;font-size:.72rem;text-transform:uppercase;letter-spacing:.12em;color:#67e8f9}.news-atlas-head h3{margin:2px 0 0;font-size:1.15rem}.news-atlas-head span{font-size:.75rem;color:#94a3b8;text-align:right}.news-atlas-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:1px;background:rgba(148,163,184,.14)}.news-atlas-panel{position:relative;height:168px;background-repeat:no-repeat;background-color:#e2e8f0;overflow:hidden}.news-atlas-world{background-size:100% 100%;background-position:center}.news-atlas-region{background-size:360% auto}.news-atlas-panel:after{content:"";position:absolute;inset:0;background:linear-gradient(to top,rgba(2,6,23,.82),transparent 58%)}.news-atlas-panel b{position:absolute;left:10px;top:9px;z-index:2;padding:3px 6px;border-radius:6px;background:rgba(2,6,23,.72);font-size:.68rem;color:white}.news-atlas-panel span{position:absolute;left:10px;right:10px;bottom:9px;z-index:2;font-size:.69rem;line-height:1.35;color:#f8fafc}.news-atlas-panel i{position:absolute;z-index:3;width:10px;height:10px;border-radius:50%;background:#ef4444;border:2px solid white;transform:translate(-50%,-50%);box-shadow:0 0 0 4px rgba(239,68,68,.22)}@media(max-width:700px){.news-atlas-grid{grid-template-columns:1fr}.news-atlas-panel{height:150px}.news-atlas-map{max-width:390px}.news-atlas-head{align-items:flex-start;flex-direction:column}.news-atlas-head span{text-align:left}}`}</style></>;
}
