/**
 * ResultPulse starts with official, high-value exam/recruitment authorities.
 * Discovery is deterministic and source-grounded: AI is not required to
 * decide whether an official result/admit-card/notification exists.
 */
export const EXAM_OFFICIAL_SOURCES = [
  {
    id: "upsc",
    name: "UPSC",
    agency: "Union Public Service Commission",
    group: "UPSC",
    url: "https://www.upsc.gov.in/",
    fallbackUrls: [
      "https://www.upsc.gov.in/whats-new",
      "https://www.upsc.gov.in/exams-related-info/written-result",
      "https://www.upsc.gov.in/exams-related-info/exam-notification/archives",
    ],
    strategy: "links",
  },
  {
    id: "ssc",
    name: "SSC",
    agency: "Staff Selection Commission",
    group: "SSC",
    url: "https://ssc.gov.in/",
    strategy: "links",
  },
  {
    id: "nta",
    name: "NTA",
    agency: "National Testing Agency",
    group: "Entrance Exams",
    url: "https://www.nta.ac.in/NoticeBoardArchive",
    strategy: "rows",
  },
  {
    id: "ibps",
    name: "IBPS",
    agency: "Institute of Banking Personnel Selection",
    group: "Banking",
    url: "https://www.ibps.in/index.php/crp-updates/",
    strategy: "rows",
  },
  {
    id: "sbi",
    name: "SBI Careers",
    agency: "State Bank of India",
    group: "Banking",
    url: "https://sbi.co.in/web/careers/current-openings",
    strategy: "links",
  },
  {
    id: "rrcb",
    name: "Railway Recruitment Control Board",
    agency: "Ministry of Railways",
    group: "Railways",
    url: "https://rrcb.gov.in/Employment_notices.html",
    strategy: "rows",
  },
  {
    id: "rrb-cdg",
    name: "RRB Chandigarh",
    agency: "Railway Recruitment Board",
    group: "Railways",
    url: "https://www.rrbcdg.gov.in/",
    strategy: "links",
  },
  {
    id: "iaf",
    name: "Indian Air Force",
    agency: "Indian Air Force",
    group: "Defence",
    url: "https://careerairforce.gov.in/notification",
    strategy: "links",
  },
  {
    id: "navy",
    name: "Join Indian Navy",
    agency: "Indian Navy",
    group: "Defence",
    url: "https://www.joinindiannavy.gov.in/",
    strategy: "links",
  },
  {
    id: "uppsc",
    name: "UPPSC",
    agency: "Uttar Pradesh Public Service Commission",
    group: "State PSC",
    url: "https://uppsc.up.nic.in/",
    strategy: "links",
  },
  {
    id: "rpsc-results",
    name: "RPSC",
    agency: "Rajasthan Public Service Commission",
    group: "State PSC",
    url: "https://rpsc.rajasthan.gov.in/result.aspx",
    strategy: "rows",
  },
];
