"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { createMemberBrowserClient } from "@/lib/supabase/browser";

type Attempt={id:string;test_type:string;exam:string|null;status:string;total_marks:number|null;max_marks:number|null;created_at:string};
type Entitlement={credits_granted:number;credits_used:number};

export default function MemberDashboard(){
 const router=useRouter(); const [email,setEmail]=useState<string|null>(null); const [loading,setLoading]=useState(true); const [ents,setEnts]=useState<Entitlement[]>([]); const [attempts,setAttempts]=useState<Attempt[]>([]);
 useEffect(()=>{(async()=>{const s=createMemberBrowserClient();const {data:{user}}=await s.auth.getUser();if(!user){setLoading(false);return;}setEmail(user.email||"Student");const [e,a]=await Promise.all([s.from("mains_entitlements").select("credits_granted,credits_used"),s.from("mains_attempts").select("id,test_type,exam,status,total_marks,max_marks,created_at").order("created_at",{ascending:false}).limit(20)]);setEnts(e.data||[]);setAttempts((a.data||[]) as Attempt[]);setLoading(false)})()},[]);
 const credits=useMemo(()=>ents.reduce((n,e)=>n+e.credits_granted-e.credits_used,0),[ents]); const evaluated=attempts.filter(a=>a.status==="evaluated"); const avg=evaluated.length?evaluated.reduce((n,a)=>n+(a.total_marks&&a.max_marks?a.total_marks/a.max_marks*100:0),0)/evaluated.length:null;
 async function logout(){await createMemberBrowserClient().auth.signOut();router.refresh();}
 if(loading)return <main className="min-h-screen bg-[#07111f] p-10 text-white">Loading your secure workspace…</main>;
 if(!email)return <main className="min-h-screen bg-[#07111f] px-5 py-20 text-white"><div className="mx-auto max-w-xl rounded-3xl border border-slate-700 bg-slate-900 p-8"><div className="text-xs font-black uppercase tracking-[.18em] text-amber-300">CurrentPulse Membership</div><h1 className="mt-2 text-4xl font-black">Your purchases need one secure account.</h1><p className="mt-4 leading-7 text-slate-400">Sign in before buying. Payments, test credits, private answer PDFs and reports stay tied to the same account.</p><Link href="/member/login" className="mt-6 inline-block rounded-xl bg-emerald-300 px-5 py-3 font-black text-slate-950">Sign in / Create account</Link></div></main>;
 return <main className="min-h-screen bg-[#07111f] px-5 py-14 text-white"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-xs font-black uppercase tracking-[.2em] text-amber-300">CurrentPulse Student Workspace</div><h1 className="mt-3 text-4xl font-black">My Mains Dashboard</h1><p className="mt-2 text-slate-400">Signed in as {email}</p></div><button onClick={logout} className="rounded-xl border border-slate-600 px-4 py-2 text-sm font-bold">Sign out</button></div>
 <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Test credits",credits],["Submitted",attempts.length],["Evaluated",evaluated.length],["Average score",avg===null?"—":`${avg.toFixed(1)}%`]].map(([a,b])=><div key={String(a)} className="rounded-2xl border border-slate-700 bg-slate-900 p-5"><div className="text-sm font-bold text-slate-400">{a}</div><div className="mt-2 text-3xl font-black text-emerald-300">{b}</div></div>)}</div>
 <div className="mt-8 grid gap-5 lg:grid-cols-3"><section className="rounded-2xl border border-emerald-400/25 bg-slate-900 p-6"><h2 className="text-2xl font-black">Buy Tests</h2><p className="mt-3 text-slate-400">Payments are verified server-side before credits are issued.</p><Link href="/member/shop" className="mt-5 inline-block rounded-xl bg-emerald-300 px-4 py-3 font-black text-slate-950">Open secure shop →</Link></section><section className="rounded-2xl border border-slate-700 bg-slate-900 p-6"><h2 className="text-2xl font-black">Answer Writing</h2><p className="mt-3 text-slate-400">Use credits for handwritten PDF evaluation.</p><Link href="/mains/answer-writing" className="mt-5 inline-block font-bold text-cyan-300">Choose test →</Link></section><section className="rounded-2xl border border-amber-300/25 bg-slate-900 p-6"><h2 className="text-2xl font-black">My Library</h2><p className="mt-3 text-slate-400">Paid digital resources will unlock here after verified purchase.</p><Link href="/mains/essay" className="mt-5 inline-block font-bold text-amber-300">Essay Book →</Link></section></div>
 <section className="mt-8 rounded-3xl border border-cyan-400/20 bg-slate-900 p-7"><h2 className="text-2xl font-black">Submission & Evaluation History</h2>{attempts.length===0?<p className="mt-4 text-slate-500">No submissions yet.</p>:<div className="mt-5 space-y-3">{attempts.map(a=><div key={a.id} className="flex flex-wrap justify-between gap-3 rounded-xl border border-slate-700 p-4"><div><div className="font-bold">{a.test_type}</div><div className="text-xs text-slate-500">{a.exam||"Subjective exam"} · {new Date(a.created_at).toLocaleDateString()}</div></div><div className="text-right"><div className="font-bold text-cyan-300">{a.status.replaceAll("_"," ")}</div><div className="text-sm text-slate-400">{a.total_marks!=null?`${a.total_marks}/${a.max_marks}`:"Awaiting score"}</div></div></div>)}</div>}</section>
 </div></main>}
