begin;

-- Preserve the image found during collection all the way through the queue.
alter table public.article_queue
  add column if not exists image_url text;

-- Article-specific visual and retention aids generated from verified content.
alter table public.articles
  add column if not exists image_search_query text,
  add column if not exists image_source_url text,
  add column if not exists visual_summary text,
  add column if not exists memory_trick text,
  add column if not exists map_locations jsonb not null default '[]'::jsonb;

-- One generated batch is stored and reused by every student. This keeps the
-- quiz fast and prevents an AI request on every page view.
create table if not exists public.quiz_questions (
  id bigint generated by default as identity primary key,
  quiz_date date not null default ((now() at time zone 'Asia/Kolkata')::date),
  prompt text not null,
  options jsonb not null,
  correct_index integer not null check (correct_index between 0 and 3),
  explanation text not null,
  difficulty text not null default 'Moderate'
    check (difficulty in ('Easy', 'Moderate', 'Difficult')),
  category text,
  paper text not null default 'Prelims',
  source_article_id bigint references public.articles(id) on delete set null,
  source_slug text,
  source_title text,
  question_hash text not null,
  generation_provider text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint quiz_questions_four_options
    check (jsonb_typeof(options) = 'array' and jsonb_array_length(options) = 4),
  constraint quiz_questions_daily_unique unique (quiz_date, question_hash)
);

create index if not exists quiz_questions_date_idx
  on public.quiz_questions (quiz_date desc, created_at asc);

create index if not exists quiz_questions_source_article_idx
  on public.quiz_questions (source_article_id);

alter table public.quiz_questions enable row level security;

drop policy if exists "Public can read quiz questions" on public.quiz_questions;
create policy "Public can read quiz questions"
  on public.quiz_questions
  for select
  to anon, authenticated
  using (true);

grant select on public.quiz_questions to anon, authenticated;
grant all on public.quiz_questions to service_role;
grant usage, select on sequence public.quiz_questions_id_seq to service_role;

commit;
