-- CurrentPulse coaching coverage queue upgrade.
-- Safe to run more than once in the Supabase SQL Editor.

begin;

alter table public.article_queue
  add column if not exists pipeline_kind text not null default 'news',
  add column if not exists coverage_event_key text,
  add column if not exists coverage_sources jsonb not null default '[]'::jsonb,
  add column if not exists target_article_id bigint references public.articles(id) on delete set null;

alter table public.article_queue
  drop constraint if exists article_queue_pipeline_kind_check;

alter table public.article_queue
  add constraint article_queue_pipeline_kind_check
  check (pipeline_kind in ('news', 'coaching', 'coaching_enrichment'));

create unique index if not exists article_queue_coverage_event_key_unique
  on public.article_queue (coverage_event_key);

create index if not exists article_queue_pipeline_status_idx
  on public.article_queue (pipeline_kind, status, importance desc, created_at asc);

create index if not exists article_queue_target_article_idx
  on public.article_queue (target_article_id)
  where target_article_id is not null;

create table if not exists public.automation_runs (
  id bigint generated by default as identity primary key,
  job_type text not null,
  status text not null default 'running',
  summary jsonb not null default '{}'::jsonb,
  error text,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint automation_runs_job_type_check
    check (job_type in ('auto_publish', 'process_queue')),
  constraint automation_runs_status_check
    check (status in ('running', 'success', 'failed'))
);

create index if not exists automation_runs_job_started_idx
  on public.automation_runs (job_type, started_at desc);

alter table public.automation_runs enable row level security;

grant select, insert, update on public.article_queue to service_role;
grant select, insert, update on public.automation_runs to service_role;
grant usage, select on sequence public.automation_runs_id_seq to service_role;

comment on column public.article_queue.coverage_sources is
  'Complete trusted coaching-source bundle retained until publication or enrichment succeeds.';

comment on column public.article_queue.pipeline_kind is
  'Separates AI news candidates from trusted coaching publication and enrichment jobs.';

commit;
