-- CurrentPulse AI integrated production upgrade
-- Content quality, hybrid sources, article visuals, quiz storage and indexes.
-- Safe to run more than once in the Supabase SQL Editor.

begin;

alter table public.article_queue
  add column if not exists image_url text;

alter table public.articles
  add column if not exists image_alt text,
  add column if not exists image_caption text,
  add column if not exists image_source_url text,
  add column if not exists image_search_query text,
  add column if not exists visual_summary text,
  add column if not exists memory_trick text,
  add column if not exists map_locations jsonb not null default '[]'::jsonb,
  add column if not exists syllabus_linkage text,
  add column if not exists india_relevance text,
  add column if not exists static_foundation text,
  add column if not exists data_examples text,
  add column if not exists answer_framework text,
  add column if not exists quality_score smallint not null default 0,
  add column if not exists quality_flags jsonb not null default '[]'::jsonb,
  add column if not exists quality_version smallint not null default 0;

alter table public.articles
  drop constraint if exists articles_quality_score_range;
alter table public.articles
  add constraint articles_quality_score_range
  check (quality_score between 0 and 100);

create index if not exists articles_quality_backfill_idx
  on public.articles (status, quality_version, quality_score, created_at desc);

create table if not exists public.article_sources (
  id bigint generated by default as identity primary key,
  article_id bigint not null references public.articles(id) on delete cascade,
  event_key text,
  source_key text not null,
  source_kind text not null default 'coaching',
  source_name text not null,
  source_title text,
  source_url text not null,
  source_published_at timestamptz,
  content_hash text,
  merged_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint article_sources_source_key_unique unique (source_key)
);

create index if not exists article_sources_article_id_idx
  on public.article_sources(article_id);
create index if not exists article_sources_event_key_idx
  on public.article_sources(event_key);
create index if not exists article_sources_created_at_idx
  on public.article_sources(created_at desc);

alter table public.article_sources enable row level security;
drop policy if exists "Public can read article sources" on public.article_sources;
create policy "Public can read article sources"
  on public.article_sources for select to anon, authenticated using (true);

create table if not exists public.quiz_questions (
  id bigint generated by default as identity primary key,
  quiz_date date not null default ((now() at time zone 'Asia/Kolkata')::date),
  prompt text not null,
  options jsonb not null,
  correct_index integer not null check (correct_index between 0 and 3),
  explanation text not null,
  difficulty text not null default 'Moderate'
    check (difficulty in ('Easy', 'Moderate', 'Difficult')),
  category text,
  paper text not null default 'Prelims',
  source_article_id bigint references public.articles(id) on delete set null,
  source_slug text,
  source_title text,
  question_hash text not null,
  generation_provider text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint quiz_questions_four_options
    check (jsonb_typeof(options) = 'array' and jsonb_array_length(options) = 4),
  constraint quiz_questions_daily_unique unique (quiz_date, question_hash)
);

create index if not exists quiz_questions_date_idx
  on public.quiz_questions (quiz_date desc, created_at asc);
create index if not exists quiz_questions_source_article_idx
  on public.quiz_questions (source_article_id);

alter table public.quiz_questions enable row level security;
drop policy if exists "Public can read quiz questions" on public.quiz_questions;
create policy "Public can read quiz questions"
  on public.quiz_questions for select to anon, authenticated using (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'article-images',
  'article-images',
  true,
  6291456,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can read article images" on storage.objects;
create policy "Public can read article images"
  on storage.objects for select to public
  using (bucket_id = 'article-images');

grant select on public.article_sources to anon, authenticated;
grant all on public.article_sources to service_role;
grant usage, select on sequence public.article_sources_id_seq to service_role;
grant select on public.quiz_questions to anon, authenticated;
grant all on public.quiz_questions to service_role;
grant usage, select on sequence public.quiz_questions_id_seq to service_role;
grant select, insert, update on public.article_queue to service_role;

comment on column public.articles.syllabus_linkage is
  'Exact Prelims and Mains syllabus linkage for the current event.';
comment on column public.articles.static_foundation is
  'Stable concepts, laws, institutions, geography or science linked to the event.';
comment on column public.articles.data_examples is
  'Source-grounded data, reports, cases and examples for answer enrichment.';

commit;
