begin;

create table if not exists public.article_sources (
  id bigint generated by default as identity primary key,
  article_id bigint not null references public.articles(id) on delete cascade,
  event_key text,
  source_key text not null,
  source_kind text not null default 'coaching',
  source_name text not null,
  source_title text,
  source_url text not null,
  source_published_at timestamptz,
  content_hash text,
  merged_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint article_sources_source_key_unique unique (source_key)
);

create index if not exists article_sources_article_id_idx
  on public.article_sources(article_id);

create index if not exists article_sources_event_key_idx
  on public.article_sources(event_key);

create index if not exists article_sources_created_at_idx
  on public.article_sources(created_at desc);

alter table public.article_sources enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'article_sources'
      and policyname = 'Public can read article sources'
  ) then
    create policy "Public can read article sources"
      on public.article_sources
      for select
      to anon, authenticated
      using (true);
  end if;
end
$$;

grant select on public.article_sources to anon, authenticated;
grant all on public.article_sources to service_role;
grant usage, select on sequence public.article_sources_id_seq to service_role;

commit;
