"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { createMemberBrowserClient } from "@/lib/supabase/browser";

const MAX_BYTES=25*1024*1024;
const testTypes=["Daily Mains Sprint","Custom Subjective Test","GS Sectional Test","Essay Writing Test","Full-Length Mains Test"];

export default function SubmitAnswerPage(){
 const router=useRouter(); const [ready,setReady]=useState(false); const [signedIn,setSignedIn]=useState(false); const [credits,setCredits]=useState(0); const [file,setFile]=useState<File|null>(null); const [testType,setTestType]=useState(testTypes[0]); const [exam,setExam]=useState("UPSC CSE Mains"); const [subject,setSubject]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
 useEffect(()=>{(async()=>{try{const s=createMemberBrowserClient();const {data:{user},error:userError}=await s.auth.getUser();if(userError)throw userError;if(!user)return;setSignedIn(true);const {data,error}=await s.from("mains_entitlements").select("credits_granted,credits_used");if(error)throw error;setCredits((data||[]).reduce((n,e)=>n+e.credits_granted-e.credits_used,0));}catch(e){setMessage(e instanceof Error?e.message:"Could not load your test credits.")}finally{setReady(true)}})()},[]);
 function choose(f:File|null){setMessage("");if(!f){setFile(null);return;}if(f.type!=="application/pdf"&&!f.name.toLowerCase().endsWith(".pdf")){setFile(null);setMessage("Upload a PDF only.");return;}if(f.size<=0||f.size>MAX_BYTES){setFile(null);setMessage("PDF must be between 1 byte and 25 MB.");return;}setFile(f)}
 async function submit(e:FormEvent){e.preventDefault();if(!file||busy)return;if(credits<1){setMessage("You do not have an unused test credit. Purchase a test/package before submitting.");return;}setBusy(true);setMessage("");const s=createMemberBrowserClient();let path="";try{const {data:{user},error:userError}=await s.auth.getUser();if(userError||!user)throw new Error("Your session expired. Sign in again.");path=`${user.id}/${crypto.randomUUID()}.pdf`;const {error:uploadError}=await s.storage.from("mains-answer-sheets").upload(path,file,{contentType:"application/pdf",upsert:false});if(uploadError)throw uploadError;const {error}=await s.rpc("submit_mains_answer",{p_answer_pdf_path:path,p_test_type:testType,p_exam:exam.trim(),p_subject:subject.trim()||null});if(error)throw error;setMessage("Answer PDF submitted securely. One test credit was consumed and your attempt is now in your submission history.");setFile(null);setCredits(c=>Math.max(0,c-1));setTimeout(()=>{router.push("/member");router.refresh()},1200);}catch(err){if(path){const {error:cleanupError}=await s.storage.from("mains-answer-sheets").remove([path]);if(cleanupError)console.error("Failed to clean up uncommitted answer PDF",cleanupError);}setMessage(err instanceof Error?err.message:"Submission failed. Your credit was not consumed unless the attempt was created.");}finally{setBusy(false)}}
 if(!ready)return <main className="min-h-screen bg-[#07111f] p-10 text-white">Loading secure submission…</main>;
 if(!signedIn)return <main className="min-h-screen bg-[#07111f] px-5 py-20 text-white"><div className="mx-auto max-w-xl rounded-3xl border border-slate-700 bg-slate-900 p-8"><h1 className="text-3xl font-black">Sign in to submit an answer</h1><p className="mt-3 text-slate-400">Your PDF, test credit and evaluation must belong to the same authenticated account.</p><Link href="/member/login" className="mt-6 inline-block rounded-xl bg-emerald-300 px-5 py-3 font-black text-slate-950">Sign in →</Link></div></main>;
 return <main className="min-h-screen bg-[#07111f] px-5 py-14 text-white"><div className="mx-auto max-w-2xl"><Link href="/member" className="text-sm font-bold text-emerald-300">← My dashboard</Link><div className="mt-6 rounded-3xl border border-cyan-400/20 bg-slate-900 p-7 sm:p-9"><div className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Private Answer Submission</div><h1 className="mt-2 text-4xl font-black">Upload handwritten answer PDF</h1><p className="mt-3 leading-7 text-slate-400">The PDF stays in private member storage. A credit is consumed only when the database successfully creates your attempt.</p><div className="mt-5 rounded-xl border border-emerald-300/20 bg-emerald-300/5 p-4"><span className="font-bold text-slate-300">Available test credits:</span> <span className="ml-2 text-2xl font-black text-emerald-300">{credits}</span></div>
 <form onSubmit={submit} className="mt-7 space-y-5"><label className="block"><span className="mb-2 block text-sm font-bold">Test type</span><select value={testType} onChange={e=>setTestType(e.target.value)} className="w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3">{testTypes.map(x=><option key={x}>{x}</option>)}</select></label><label className="block"><span className="mb-2 block text-sm font-bold">Exam</span><input required maxLength={100} value={exam} onChange={e=>setExam(e.target.value)} className="w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3" /></label><label className="block"><span className="mb-2 block text-sm font-bold">Subject / paper <span className="font-normal text-slate-500">(optional)</span></span><input maxLength={120} value={subject} onChange={e=>setSubject(e.target.value)} placeholder="e.g. GS-II, History Optional, Essay" className="w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3" /></label><label className="block rounded-2xl border border-dashed border-slate-600 bg-slate-950/60 p-5"><span className="block font-black">Answer PDF</span><span className="mt-1 block text-xs text-slate-500">PDF only · maximum 25 MB · clear upright scans recommended</span><input required type="file" accept="application/pdf,.pdf" onChange={e=>choose(e.target.files?.[0]||null)} className="mt-4 block w-full text-sm" />{file&&<span className="mt-2 block text-sm text-emerald-300">Selected: {file.name} · {(file.size/1024/1024).toFixed(2)} MB</span>}</label><button disabled={busy||!file||credits<1} className="w-full rounded-xl bg-emerald-300 px-5 py-4 font-black text-slate-950 disabled:cursor-not-allowed disabled:opacity-50">{busy?"Uploading securely…":credits<1?"No test credit available":"Submit answer · use 1 credit"}</button></form>
 {credits<1&&<p className="mt-4 text-sm text-amber-200">You need a test credit before submitting. <Link href="/member/shop" className="font-black underline">View tests and packages</Link>.</p>}{message&&<div aria-live="polite" className="mt-5 rounded-xl border border-amber-300/20 bg-amber-300/10 p-4 text-sm leading-6 text-amber-100">{message}</div>}<p className="mt-6 text-xs leading-5 text-slate-500">Do not upload identity documents or unrelated personal records. Low-readability answer sheets should be flagged for rescan rather than guessed during evaluation.</p></div></div></main>;
}
