export const CA_PDF_LIVE_QUALITY_GATE_VERSION = 1;

export const CA_PDF_REQUIRED_LIVE_SECTIONS = Object.freeze([
  "FAST READ",
  "WHY IN NEWS",
  "TOP DATA & FACTS",
  "PRELIMS",
  "QUICK REVISION",
  "PROBABLE OBJECTIVE QUESTION",
  "PROBABLE MAINS QUESTION",
  "MODEL ANSWER (~300 WORDS)",
  "SOURCES",
]);
