import Link from "next/link";

export const metadata={title:"Handwritten Answer Evaluation | UPSC, PCS & Subjective Exams",description:"AI-assisted handwritten answer evaluation, paid tests and discounted packages with private member PDF submission."};
const tests=[
{name:"Daily Mains Sprint",tag:"UPSC / PCS",price:"₹29",meta:"3 questions • 45 min",copy:"Fast daily handwritten practice with question-wise evaluation."},
{name:"GS Sectional Test",tag:"UPSC GS1–GS4 / PCS",price:"₹79",meta:"10 questions • 90 min",copy:"Syllabus-wise test with 10/15-marker questions and structured evaluation."},
{name:"Full-Length Mains Test",tag:"UPSC / State PCS",price:"₹149",meta:"20 questions • 3 hours",copy:"Exam-condition full paper with paper-level performance review."},
{name:"Essay Writing Test",tag:"UPSC / PCS Essay",price:"₹99",meta:"2 essays • 3 hours",copy:"Essay evaluation for interpretation, structure, dimensions, examples, coherence and conclusion."},
{name:"Custom Subjective Test",tag:"PCS / University / Other",price:"₹59",meta:"Choose subject • Flexible",copy:"History, Political Science, Geography and other descriptive examinations."}];
const packages=[
{name:"Starter Pack",tests:"5 tests",price:"₹299",old:"₹395",saving:"Save ₹96"},
{name:"Practice Pack",tests:"10 tests",price:"₹549",old:"₹790",saving:"Save ₹241",popular:true},
{name:"Serious Mains Pack",tests:"20 tests",price:"₹999",old:"₹1,580",saving:"Save ₹581"},
{name:"Mains Marathon",tests:"30 tests",price:"₹1,399",old:"₹2,370",saving:"Save ₹971"},
{name:"Complete 50-Test Pack",tests:"50 tests",price:"₹1,999",old:"₹3,950",saving:"Save ₹1,951"}];
const checks=["Question-demand fulfilment","10/15/20-marker depth","Introduction & conclusion","Headings and answer structure","Facts, data & current examples","Constitutional/legal anchors","Multidimensional coverage","Maps, diagrams & flowcharts","Word-limit discipline","Presentation & readability","Missing high-value points","Actionable improvement plan"];
export default function AnswerWritingPage(){return <main className="min-h-screen bg-[#07111f] text-slate-100">
<section className="border-b border-emerald-300/20 bg-[radial-gradient(circle_at_top_left,_#123c3a_0,_#07111f_48%,_#030712_100%)]"><div className="mx-auto max-w-7xl px-5 py-16 sm:py-20"><div className="inline-flex rounded-full border border-emerald-300/40 bg-emerald-300/10 px-4 py-2 text-xs font-black uppercase tracking-[.2em] text-emerald-200">Handwritten Answer Evaluation</div><h1 className="mt-5 max-w-5xl text-4xl font-black leading-tight sm:text-6xl">Write on paper. Upload PDF. <span className="text-emerald-300">Get structured evaluation.</span></h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">Built for real handwritten UPSC, PCS and descriptive-exam answers. The evaluation pipeline first checks scan readability, then reads the answer, applies the exam rubric and audits the proposed score before publishing feedback.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#packages" className="rounded-xl bg-amber-300 px-5 py-3 font-black text-slate-950">View Packages</a><a href="#evaluation" className="rounded-xl bg-emerald-300 px-5 py-3 font-black text-slate-950">How Checking Works</a><Link href="/member" className="rounded-xl border border-slate-500 px-5 py-3 font-bold">Member Dashboard</Link></div></div></section>
<section id="evaluation" className="mx-auto max-w-7xl px-5 py-12"><div className="grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border border-cyan-400/20 bg-slate-900 p-7"><div className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">High-Efficiency Pipeline</div><h2 className="mt-2 text-3xl font-black">5-stage handwritten checking</h2><div className="mt-6 space-y-3">{["1. Scan Quality Gate — detect blur, faint pages, rotation and unreadable handwriting before evaluation.","2. Visual Reading — read handwriting, page layout, headings, diagrams, maps and flowcharts.","3. Rubric Evaluation — score each answer against exam, marks and question demand.","4. Independent Score Audit — second pass challenges unsupported marks and checks missed strengths/weaknesses.","5. Student Report — question-wise marks, evidence, missing points and specific improvement actions."].map(x=><div key={x} className="rounded-xl border border-slate-700 bg-slate-950/50 p-4 text-sm leading-6 text-slate-300">{x}</div>)}</div></div><div className="rounded-3xl border border-emerald-400/20 bg-slate-900 p-7"><div className="text-xs font-black uppercase tracking-[.18em] text-emerald-300">Evaluation Rubric</div><h2 className="mt-2 text-3xl font-black">What every answer is checked for</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{checks.map(x=><div key={x} className="rounded-xl bg-emerald-300/5 p-3 text-sm font-bold text-slate-300">✓ {x}</div>)}</div><div className="mt-5 rounded-xl border border-amber-300/20 bg-amber-300/5 p-4 text-sm leading-6 text-amber-100"><b>Reliability rule:</b> unreadable or low-confidence pages should be flagged for rescan instead of guessing content or marks.</div></div></div></section>
<section id="packages" className="mx-auto max-w-7xl px-5 py-12"><div className="mb-7"><div className="text-sm font-black uppercase tracking-[.18em] text-amber-300">Save More • Practice More</div><h2 className="mt-2 text-3xl font-black">Handwritten Test Packages</h2></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-5">{packages.map(p=><article key={p.name} className={`relative flex flex-col rounded-2xl border p-6 ${p.popular?"border-amber-300 bg-amber-300/10":"border-slate-700 bg-slate-900/75"}`}>{p.popular&&<div className="absolute -top-3 left-5 rounded-full bg-amber-300 px-3 py-1 text-xs font-black uppercase text-slate-950">Most Popular</div>}<div className="text-xs font-black uppercase tracking-[.15em] text-amber-300">{p.tests}</div><h3 className="mt-2 text-xl font-black">{p.name}</h3><div className="mt-5 flex items-end gap-2"><span className="text-3xl font-black">{p.price}</span><span className="pb-1 text-sm text-slate-500 line-through">{p.old}</span></div><div className="mt-1 text-sm font-black text-emerald-300">{p.saving}</div><Link href="/member" className="mt-6 rounded-xl bg-amber-300 px-4 py-3 text-center font-black text-slate-950">Sign in to Buy →</Link></article>)}</div></section>
<section id="tests" className="mx-auto max-w-7xl px-5 py-12"><div className="mb-7"><div className="text-sm font-bold uppercase tracking-[.18em] text-emerald-300">5 Single-Test Formats</div><h2 className="mt-2 text-3xl font-black">UPSC, PCS, Essay and other subjective exams</h2></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{tests.map((t,i)=><article key={t.name} className="flex flex-col rounded-2xl border border-slate-700 bg-slate-900/75 p-6"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-black uppercase tracking-[.15em] text-emerald-300">Test {i+1} • {t.tag}</div><h3 className="mt-2 text-2xl font-black">{t.name}</h3></div><div className="rounded-xl bg-emerald-300 px-3 py-2 text-xl font-black text-slate-950">{t.price}</div></div><div className="mt-4 font-bold">{t.meta}</div><p className="mt-3 flex-1 leading-7 text-slate-400">{t.copy}</p><Link href="/member" className="mt-6 rounded-xl border border-emerald-300/40 bg-emerald-300/10 px-4 py-3 text-center font-black text-emerald-200">Sign in to Buy & Attempt →</Link></article>)}</div></section>
<section className="mx-auto max-w-7xl px-5 pb-16"><div className="rounded-3xl border border-amber-300/20 bg-slate-900 p-7 sm:p-10"><div className="text-sm font-bold uppercase tracking-[.2em] text-amber-300">Student Workflow</div><h2 className="mt-2 text-3xl font-black">Buy → Handwrite → Scan → Upload PDF → Quality Gate → Evaluate → Audit → Report</h2><p className="mt-5 leading-7 text-slate-400">Answer PDFs remain tied to the authenticated student's attempt. Payment and package credits must be verified server-side. AI-generated evaluation should be labelled as AI evaluation, with low-confidence handwriting escalated for rescan rather than silently scored.</p></div></section>
</main>}
