import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
function load(relative){return fs.readFileSync(new URL(`../${relative}`,import.meta.url),"utf8");}
async function loadResolver(){const deadlineUrl=pathToFileURL(path.resolve(process.cwd(),"lib/network/deadline.js")).href;const source=load("lib/news/governmentImageResolver.js").replace('"@/lib/network/deadline"',JSON.stringify(deadlineUrl));const temp=path.resolve(process.cwd(),"tests/.tmp-government-image-resolver.mjs");fs.writeFileSync(temp,source,"utf8");return{resolver:await import(`${pathToFileURL(temp).href}?v=${Date.now()}`),cleanup:()=>fs.rmSync(temp,{force:true})};}
test("image resolver uses bounded Wikimedia, Openverse and NASA priority",async()=>{const{resolver,cleanup}=await loadResolver();try{assert.deepEqual(resolver.governmentImageProviderPriority("Space"),["wikimedia","nasa","openverse"]);assert.deepEqual(resolver.governmentImageProviderPriority("Environment"),["wikimedia","openverse"]);let calls=0;const urls=[];const result=await resolver.resolveGovernmentArticleImage({title:"Example cyclone",category:"Environment"},{fetch:async(url)=>{calls+=1;urls.push(String(url));return{ok:true,json:async()=>String(url).includes("openverse")?{results:[]}:{query:{pages:{}}}};}});assert.equal(calls,3);assert.ok(urls.some((url)=>url.includes("commons.wikimedia.org")));assert.ok(urls.some((url)=>url.includes("api.openverse.org")));assert.equal(result.resolution.status,"no_safe_image");assert.equal(result.resolution.requests_used,3);assert.equal(result.resolution.provider,"multi_source");}finally{cleanup();}});
test("terminal resolver state prevents any repeat request",async()=>{const{resolver,cleanup}=await loadResolver();try{const previous={status:"no_safe_image",provider:"pib",requests_used:1};const result=await resolver.resolveGovernmentArticleImage({title:"Policy",category:"Government policy",image_resolution:previous},{fetch:async()=>{throw new Error("must not fetch");}});assert.equal(result.searched,false);assert.equal(result.resolution,previous);}finally{cleanup();}});
test("publication, admin PDF import and explicit backfill share one resolve-once image policy",()=>{const publisher=load("lib/publisher/publishArticle.js");const pdfPublisher=load("app/api/admin/pdf-import/publish/route.js");const backfill=load("app/api/backfill-images/route.js");const publicPage=load("app/news/[slug]/page.js");const migration=load("supabase/migrations/20260824112805_article_image_resolution.sql");assert.match(publisher,/resolveGovernmentArticleImage/);assert.match(pdfPublisher,/resolveGovernmentArticleImage/);assert.match(pdfPublisher,/image_resolution/);assert.match(backfill,/resolveGovernmentArticleImage/);assert.match(backfill,/isTerminalImageResolution/);assert.match(backfill,/hotlink/);assert.match(publicPage,/\.select\("\*,article_sources/);assert.match(migration,/add column if not exists image_resolution jsonb/);});
