import { deadlineSignal, remainingDeadlineMs } from "@/lib/network/deadline";

export const IMAGE_RESOLVER_VERSION = 2;
export const TERMINAL_IMAGE_RESOLUTION_STATUSES=new Set(["resolved","no_safe_image","preserved_existing","rejected"]);
const PROVIDERS={
  official:{usage:"official_site_reuse_policy"},
  wikimedia:{usage:"wikimedia_commons_file_license",imageHosts:["upload.wikimedia.org","commons.wikimedia.org"]},
  openverse:{usage:"creative_commons_verified",imageHosts:["api.openverse.org","images.openverse.org"]},
  nasa:{usage:"nasa_media_usage",imageHosts:["images-assets.nasa.gov","nasa.gov"]},
  unsplash:{usage:"unsplash_api_license",imageHosts:["images.unsplash.com"]},
  pexels:{usage:"pexels_license",imageHosts:["images.pexels.com"]},
  pixabay:{usage:"pixabay_content_license",imageHosts:["cdn.pixabay.com","pixabay.com"]},
};
function clean(v=""){return String(v||"").replace(/<[^>]*>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/\s+/g," ").trim();}
function hostname(v=""){try{return new URL(v).hostname.toLowerCase();}catch{return"";}}
function isProviderHost(url,p){const h=hostname(url);return(PROVIDERS[p]?.imageHosts||[]).some(a=>h===a||h.endsWith(`.${a}`));}
function safeWikimediaLicense(v=""){const x=clean(v).toLowerCase();return Boolean(x&&!/non.?commercial|no.?derivatives|all rights reserved|fair use/.test(x)&&/public domain|cc0|creative commons|cc by|cc-by|gfdl/.test(x));}
function safeOpenverseLicense(v=""){return/^(cc0|by|by-sa|pdm)$/i.test(clean(v));}
function extractUrls(v=""){return[...String(v||"").matchAll(/https?:\/\/[^\s)\]>]+/gi)].map(m=>m[0].replace(/[.,;]+$/,""));}
function officialUrls(a={}){const text=[a.source_url,a.image_source_url,a.why_news,a.content,a.static_foundation,a.data_examples].filter(Boolean).join("\n");return[...new Set(extractUrls(text).filter(u=>{const h=hostname(u);return h==="pib.gov.in"||h.endsWith(".pib.gov.in")||h==="pmindia.gov.in"||h.endsWith(".pmindia.gov.in");}))].slice(0,2);}
function htmlMeta(html,name){const e=name.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");for(const r of[new RegExp(`<meta[^>]+(?:property|name)=["']${e}["'][^>]+content=["']([^"']+)["']`,`i`),new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${e}["']`,`i`)]){const m=String(html||"").match(r);if(m?.[1])return m[1].replace(/&amp;/g,"&");}return"";}
function tokenSet(v=""){return new Set(clean(v).toLowerCase().split(/[^a-z0-9]+/).filter(x=>x.length>2&&!/^(india|indian|news|current|affairs|today|year)$/.test(x)));}
function relevanceScore(q,...vals){const qs=tokenSet(q),hay=tokenSet(vals.join(" "));let n=0;for(const t of qs)if(hay.has(t))n++;return n;}
function terminal(status,provider,requestsUsed,extra={}){return{status,provider:provider||"currentpulse_fallback",resolver_version:IMAGE_RESOLVER_VERSION,attempted_at:new Date().toISOString(),requests_used:requestsUsed,attribution:extra.attribution||"",license_or_usage:extra.license_or_usage||"",source_page_url:extra.source_page_url||"",search_query:extra.search_query||""};}
export function isTerminalImageResolution(v){
 if(!v||!TERMINAL_IMAGE_RESOLUTION_STATUSES.has(v.status))return false;
 // A previous no-safe result must be retried after the resolver itself changes.
 return v.status!=="no_safe_image"||Number(v.resolver_version)===IMAGE_RESOLVER_VERSION;
}
export function governmentImageProviderPriority(category=""){return/space|astronomy/i.test(String(category))?["wikimedia","nasa"]:["wikimedia","openverse"];}
function imageQuery(article={}){const title=clean(article.title),body=clean(`${article.why_news||""} ${article.content||""}`).slice(0,4500);const rules=[
[/Modi.*Putin|Putin.*Modi|Shanghai Cooperation|\bSCO\b/i,"Narendra Modi Vladimir Putin SCO summit meeting"],[/Kavach|automatic train protection/i,"Indian Railways Kavach train"],[/Afghanistan.*trade|India.*Afghanistan/i,"India Afghanistan trade meeting"],[/Tiger Landscapes|tiger.*ecotourism/i,"India tiger reserve landscape"],[/Districts as Export Hubs|export hubs/i,"India district exports MSME products"],[/Jal Jeevan Mission|Water Security Departmental Summit/i,"Jal Jeevan Mission rural water India"],[/EPFO Amnesty|provident fund/i,"EPFO office workers India"],[/nuclear energy|nuclear power|reactor|100 GW/i,"nuclear power plant India"],[/Aditya.L1|solar flare|space weather/i,"Aditya L1 ISRO Sun"],[/Magnetar|neutron star/i,"magnetar neutron star"],[/Assam Flood|Brahmaputra.*flood/i,"Brahmaputra Assam flood"],[/UNCCD|land degraded|drought/i,"land degradation drought desertification"],[/Positive Indigenisation|defence items/i,"India defence manufacturing military equipment"],[/Nistar|Nipun|Diving Support Vessel/i,"Indian Navy diving support vessel"],[/Delhi.*pollution|winter pollution|smog/i,"Delhi air pollution smog"],[/COSCO|shipping/i,"COSCO container ship"],[/GDP|manufacturing recovery/i,"India manufacturing industry factory economy"],[/Makhana|fox nut/i,"Euryale ferox makhana Bihar"],[/Per Drop More Crop|micro.?irrigation/i,"drip irrigation agriculture India"],[/Typhoid|TCV/i,"typhoid vaccine vaccination"],[/wastewater/i,"wastewater treatment plant"],[/higher education|universit/i,"university students India higher education"],[/Jan Dhan/i,"Pradhan Mantri Jan Dhan Yojana India"],[/e-Shram/i,"workers labour India"],[/Regenerative Agriculture|natural farmers/i,"natural farming agriculture India"],[/India.Japan|Japan.*India/i,"India Japan leaders meeting"],[/India.Chile|Chile.*India/i,"India Chile diplomacy leaders"],[/ONGC|deepwater/i,"ONGC offshore oil India"],[/Sone River|Son River/i,"Son River Bihar India"],[/Nepal.*hydropower/i,"Nepal hydropower dam"],[/Ukraine.*Kyiv|Kyiv.*Ukraine/i,"Kyiv Ukraine air defence"],
];for(const[p,q]of rules)if(p.test(title)||p.test(body))return q;return title.replace(/\b(2025|2026|2027)\b/g,"").replace(/[:;|].*$/,"").replace(/\b(roadmap|analysis|explained|current affairs|news)\b/gi,"").trim().slice(0,120);}
async function officialCandidate(article,options){for(const pageUrl of officialUrls(article)){if(!remainingDeadlineMs(options.deadlineAt,900))break;const signal=deadlineSignal(options.deadlineAt,4500);if(!signal)break;try{const r=await(options.fetch||fetch)(pageUrl,{headers:{Accept:"text/html,application/xhtml+xml","User-Agent":"CurrentPulse/1.0 official image resolver"},cache:"force-cache",next:{revalidate:86400},signal});if(!r.ok||typeof r.text!=="function")continue;const html=await r.text(),image=htmlMeta(html,"og:image")||htmlMeta(html,"twitter:image");if(!/^https?:\/\//i.test(image))continue;const title=clean(htmlMeta(html,"og:title")||article.title),source=hostname(pageUrl).includes("pib.gov.in")?"Press Information Bureau":"Prime Minister of India";return{score:5,url:image,sourcePageUrl:pageUrl,attribution:`${source} · ${title}`.slice(0,700),licenseOrUsage:"Official website material - source acknowledgement required; third-party material excluded",alt:title,provider:"official"};}catch(e){console.error("[Image resolver] official page request failed:",e?.message||e);}}return null;}
function wikimediaCandidate(payload,q){let best=null;for(const p of Object.values(payload?.query?.pages||{})){const i=p?.imageinfo?.[0],m=i?.extmetadata||{},url=i?.thumburl||i?.url||"",sourcePageUrl=i?.descriptionurl||p?.canonicalurl||"";if(!url||!sourcePageUrl||!isProviderHost(url,"wikimedia")||!isProviderHost(sourcePageUrl,"wikimedia"))continue;const lic=clean(m.LicenseShortName?.value||m.UsageTerms?.value||"");if(!safeWikimediaLicense(lic))continue;const title=clean(m.ObjectName?.value||p?.title?.replace(/^File:/i,"")||""),desc=clean(m.ImageDescription?.value||""),artist=clean(m.Artist?.value||m.Credit?.value||"");if(/logo|icon|coat of arms/i.test(`${title} ${desc}`)&&!/logo/i.test(q))continue;const c={score:relevanceScore(q,title,desc)+0.3,url,sourcePageUrl,attribution:[title,artist,lic,"Wikimedia Commons"].filter(Boolean).join(" · ").slice(0,700),licenseOrUsage:lic,alt:desc||title,provider:"wikimedia"};if(!best||c.score>best.score)best=c;}return best;}
function openverseCandidate(payload,q){let best=null;for(const i of payload?.results||[]){const lic=clean(i?.license||"");if(!safeOpenverseLicense(lic))continue;const url=clean(i?.thumbnail||i?.url||""),sourcePageUrl=clean(i?.foreign_landing_url||i?.detail_url||"");if(!url||!sourcePageUrl)continue;const title=clean(i?.title||""),creator=clean(i?.creator||""),c={score:relevanceScore(q,title,i?.tags?.map?.(t=>t?.name).join(" ")||""),url,sourcePageUrl,attribution:[title,creator,lic,"via Openverse"].filter(Boolean).join(" · ").slice(0,700),licenseOrUsage:lic,alt:title||q,provider:"openverse"};if(!best||c.score>best.score)best=c;}return best;}
function nasaCandidate(payload,q){let best=null;for(const i of payload?.collection?.items||[]){const link=(i.links||[]).find(x=>x?.rel==="preview"&&isProviderHost(x.href,"nasa"));if(!link)continue;const d=i.data?.[0]||{},title=clean(d.title),desc=clean(d.description),c={score:relevanceScore(q,title,desc),url:link.href,sourcePageUrl:i.href||"",attribution:`NASA · ${title}`.slice(0,500),licenseOrUsage:PROVIDERS.nasa.usage,alt:title||desc,provider:"nasa"};if(!best||c.score>best.score)best=c;}return best;}
async function searchWikimedia(q,o){const s=deadlineSignal(o.deadlineAt,5000);if(!s)return null;const p=new URLSearchParams({action:"query",generator:"search",gsrsearch:q,gsrnamespace:"6",gsrlimit:"12",prop:"imageinfo|info",iiprop:"url|extmetadata",iiurlwidth:"1000",inprop:"url",format:"json",origin:"*"}),r=await(o.fetch||fetch)(`https://commons.wikimedia.org/w/api.php?${p}`,{headers:{Accept:"application/json","User-Agent":"CurrentPulse/1.0 Wikimedia image resolver"},cache:"force-cache",next:{revalidate:604800},signal:s});return r.ok?wikimediaCandidate(await r.json(),q):null;}
async function searchOpenverse(q,o){const s=deadlineSignal(o.deadlineAt,5000);if(!s)return null;const p=new URLSearchParams({q,page_size:"12",mature:"false"}),r=await(o.fetch||fetch)(`https://api.openverse.org/v1/images/?${p}`,{headers:{Accept:"application/json","User-Agent":"CurrentPulse/1.0 free-media resolver"},cache:"force-cache",next:{revalidate:604800},signal:s});return r.ok?openverseCandidate(await r.json(),q):null;}
async function searchNASA(q,o){const s=deadlineSignal(o.deadlineAt,5000);if(!s)return null;const r=await(o.fetch||fetch)(`https://images-api.nasa.gov/search?q=${encodeURIComponent(q)}&media_type=image&page_size=10`,{headers:{Accept:"application/json","User-Agent":"CurrentPulse/1.0 NASA media resolver"},cache:"force-cache",next:{revalidate:604800},signal:s});return r.ok?nasaCandidate(await r.json(),q):null;}
async function searchUnsplash(q,o){const key=process.env.UNSPLASH_ACCESS_KEY?.trim();if(!key)return null;const s=deadlineSignal(o.deadlineAt,4500);if(!s)return null;const p=new URLSearchParams({query:q,per_page:"10",orientation:"landscape",content_filter:"high"}),r=await(o.fetch||fetch)(`https://api.unsplash.com/search/photos?${p}`,{headers:{Accept:"application/json",Authorization:`Client-ID ${key}`},cache:"force-cache",next:{revalidate:604800},signal:s});if(!r.ok)return null;let best=null;for(const i of(await r.json())?.results||[]){const c={score:relevanceScore(q,i.alt_description,i.description),url:i.urls?.regular||i.urls?.small||"",sourcePageUrl:i.links?.html||"",attribution:`Photo by ${clean(i.user?.name)} on Unsplash`,licenseOrUsage:PROVIDERS.unsplash.usage,alt:clean(i.alt_description||i.description||q),provider:"unsplash"};if(c.url&&c.sourcePageUrl&&(!best||c.score>best.score))best=c;}return best;}
async function searchPexels(q,o){const key=process.env.PEXELS_API_KEY?.trim();if(!key)return null;const s=deadlineSignal(o.deadlineAt,4500);if(!s)return null;const p=new URLSearchParams({query:q,per_page:"10",orientation:"landscape"}),r=await(o.fetch||fetch)(`https://api.pexels.com/v1/search?${p}`,{headers:{Accept:"application/json",Authorization:key},cache:"force-cache",next:{revalidate:604800},signal:s});if(!r.ok)return null;let best=null;for(const i of(await r.json())?.photos||[]){const c={score:relevanceScore(q,i.alt,i.photographer),url:i.src?.large||i.src?.medium||"",sourcePageUrl:i.url||"",attribution:`Photo by ${clean(i.photographer)} on Pexels`,licenseOrUsage:PROVIDERS.pexels.usage,alt:clean(i.alt||q),provider:"pexels"};if(c.url&&c.sourcePageUrl&&(!best||c.score>best.score))best=c;}return best;}
async function searchPixabay(q,o){const key=process.env.PIXABAY_API_KEY?.trim();if(!key)return null;const s=deadlineSignal(o.deadlineAt,4500);if(!s)return null;const p=new URLSearchParams({key,q,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:"10"}),r=await(o.fetch||fetch)(`https://pixabay.com/api/?${p}`,{headers:{Accept:"application/json"},cache:"force-cache",next:{revalidate:604800},signal:s});if(!r.ok)return null;let best=null;for(const i of(await r.json())?.hits||[]){const c={score:relevanceScore(q,i.tags,i.user),url:i.largeImageURL||i.webformatURL||"",sourcePageUrl:i.pageURL||"",attribution:`Image by ${clean(i.user)} via Pixabay`,licenseOrUsage:PROVIDERS.pixabay.usage,alt:clean(i.tags||q),provider:"pixabay"};if(c.url&&c.sourcePageUrl&&(!best||c.score>best.score))best=c;}return best;}
export async function resolveGovernmentArticleImage(article={},options={}){
 const existing=article.image_resolution;if(isTerminalImageResolution(existing))return{image:null,resolution:existing,searched:false};if(options.preserveExisting)return{image:null,resolution:terminal("preserved_existing","existing",0,{attribution:article.image_caption,source_page_url:article.image_source_url}),searched:false};
 const q=imageQuery(article),priority=governmentImageProviderPriority(article.category),attempts=[];let requestsUsed=0;
 if(officialUrls(article).length&&remainingDeadlineMs(options.deadlineAt,900)){requestsUsed++;const c=await officialCandidate(article,options);if(c)return{image:c,searched:true,query:q,resolution:terminal("resolved","official",requestsUsed,{attribution:c.attribution,license_or_usage:c.licenseOrUsage,source_page_url:c.sourcePageUrl,search_query:q})};}
 for(const p of priority)attempts.push({provider:p,fn:p==="wikimedia"?searchWikimedia:p==="nasa"?searchNASA:searchOpenverse});
 for(const a of attempts){if(!remainingDeadlineMs(options.deadlineAt,900))break;requestsUsed++;try{const c=await a.fn(q,options);if(c&&c.score>=0.8)return{image:c,searched:true,query:q,resolution:terminal("resolved",a.provider,requestsUsed,{attribution:c.attribution,license_or_usage:c.licenseOrUsage,source_page_url:c.sourcePageUrl,search_query:q})};}catch(e){console.error(`[Image resolver] ${a.provider} request failed:`,e?.message||e);}}
 const optional=[process.env.UNSPLASH_ACCESS_KEY?.trim()&&{provider:"unsplash",fn:searchUnsplash},process.env.PEXELS_API_KEY?.trim()&&{provider:"pexels",fn:searchPexels},process.env.PIXABAY_API_KEY?.trim()&&{provider:"pixabay",fn:searchPixabay}].filter(Boolean);
 for(const a of optional){if(!remainingDeadlineMs(options.deadlineAt,900))break;requestsUsed++;try{const c=await a.fn(q,options);if(c&&c.score>=0.8)return{image:c,searched:true,query:q,resolution:terminal("resolved",a.provider,requestsUsed,{attribution:c.attribution,license_or_usage:c.licenseOrUsage,source_page_url:c.sourcePageUrl,search_query:q})};}catch(e){console.error(`[Image resolver] ${a.provider} request failed:`,e?.message||e);}}
 return{image:null,searched:requestsUsed>0,query:q,resolution:terminal("no_safe_image","multi_source",requestsUsed,{license_or_usage:"no_verified_reusable_image",search_query:q})};
}
