"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { Menu,X,Search,Bot,House,NotebookPen,LibraryBig,CircleHelp,Files,Newspaper,BookOpenCheck,GraduationCap,PenLine,UserRound } from "lucide-react";

export default function Navbar() {
 const [open,setOpen]=useState(false); const [searchOpen,setSearchOpen]=useState(false); const [query,setQuery]=useState(""); const [language,setLanguage]=useState<"en"|"hi">("en");
 const router=useRouter(); const pathname=usePathname();
 useEffect(()=>{const timer=window.setTimeout(()=>{try{setLanguage(new URLSearchParams(window.location.search).get("lang")==="hi"?"hi":"en")}catch{}},0);return()=>window.clearTimeout(timer)},[pathname]);
 const hi=language==="hi";
 const links=[
 {name:hi?"मुखपृष्ठ":"Home",href:"/",icon:House},{name:hi?"करेंट अफेयर्स":"Current Affairs",href:"/current-affairs",icon:BookOpenCheck},{name:hi?"मेन्स":"Mains",href:"/mains",icon:PenLine},{name:hi?"समाचार":"News",href:"/news",icon:Newspaper},{name:hi?"परीक्षाएँ":"Exams",href:"/exams",icon:GraduationCap},{name:hi?"मॉक टेस्ट":"Mock Tests",href:"/mock-tests",icon:CircleHelp},{name:hi?"PDF":"PDF",href:"/pdf",icon:Files},{name:hi?"नोट्स":"Notes",href:"/notes",icon:NotebookPen},{name:hi?"PYQ":"PYQs",href:"/pyq",icon:LibraryBig},{name:"AI",href:"/ai",icon:Bot}];
 function withLanguage(href:string){if(!hi)return href;return `${href}${href.includes("?")?"&":"?"}lang=hi`}
 function toggleLanguage(){const url=new URL(window.location.href);if(hi)url.searchParams.delete("lang");else url.searchParams.set("lang","hi");window.location.assign(`${url.pathname}${url.search}${url.hash}`)}
 function handleSearch(e:FormEvent<HTMLFormElement>){e.preventDefault();const clean=query.trim();if(!clean)return;router.push(`/search?q=${encodeURIComponent(clean)}${hi?"&lang=hi":""}`);setQuery("");setSearchOpen(false);setOpen(false)}
 function active(href:string){return href==="/"?pathname==="/":pathname===href||pathname.startsWith(`${href}/`)}
 return <header className="sticky top-0 z-50 border-b border-white/8 bg-slate-950/86 shadow-[0_12px_35px_rgba(2,6,23,.28)] backdrop-blur-xl">
 <div className="mx-auto flex h-[4.75rem] max-w-7xl items-center justify-between px-4 sm:px-6"><Link href={withLanguage("/")} className="group flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-gradient-to-br from-cyan-300 via-cyan-500 to-blue-600 text-lg font-black text-slate-950">CP</div><div><p className="text-lg font-black text-white">CurrentPulse AI</p><p className="text-xs text-gray-400">Daily · Static · PYQ-linked</p></div></Link>
 <nav className="hidden items-center gap-1 xl:flex">{links.map(i=><Link key={i.name} href={withLanguage(i.href)} className={`rounded-lg px-2.5 py-2 text-sm font-semibold transition ${active(i.href)?"bg-cyan-400/12 text-cyan-300":"text-slate-300 hover:bg-white/5 hover:text-white"}`}>{i.name}</Link>)}</nav>
 <div className="hidden items-center gap-2 xl:flex"><Link href="/member" className="flex items-center gap-2 rounded-xl border border-amber-300/30 bg-amber-300/10 px-3 py-2 text-sm font-black text-amber-200"><UserRound size={16}/>Member</Link><button onClick={toggleLanguage} className="rounded-xl border border-cyan-400/30 bg-cyan-400/10 px-3 py-2 text-sm font-black text-cyan-200">{hi?"EN":"हिन्दी"}</button><button onClick={()=>setSearchOpen(v=>!v)} className="rounded-xl border border-slate-700 bg-slate-900 p-3 text-slate-300">{searchOpen?<X size={18}/>:<Search size={18}/>}</button></div>
 <button onClick={()=>setOpen(v=>!v)} className="rounded-xl border border-slate-700 bg-slate-900 p-2.5 text-white xl:hidden">{open?<X size={28}/>:<Menu size={28}/>}</button></div>
 {searchOpen&&<div className="hidden border-t border-slate-800 bg-slate-950 xl:block"><form onSubmit={handleSearch} className="mx-auto flex max-w-3xl gap-3 px-6 py-5"><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search current affairs, Mains, PYQs..." className="flex-1 rounded-xl border border-slate-700 bg-slate-900 px-4 py-3 text-white outline-none"/><button className="rounded-xl bg-cyan-500 px-6 py-3 font-semibold text-black">Search</button></form></div>}
 {open&&<div className="max-h-[calc(100vh-4.75rem)] overflow-y-auto border-t border-slate-800 bg-slate-950 xl:hidden"><div className="space-y-2 p-4"><form onSubmit={handleSearch} className="mb-4 flex gap-2"><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search..." className="min-w-0 flex-1 rounded-xl border border-slate-700 bg-slate-900 px-4 py-3 text-white"/><button className="rounded-xl bg-cyan-500 px-4 text-black"><Search size={18}/></button></form><Link href="/member" onClick={()=>setOpen(false)} className="flex items-center gap-3 rounded-xl bg-amber-300/10 px-4 py-3 font-black text-amber-200"><UserRound size={18}/>Member / Purchases</Link><button onClick={toggleLanguage} className="w-full rounded-xl border border-cyan-400/30 bg-cyan-400/10 px-4 py-3 text-left font-black text-cyan-200">{hi?"Switch to English":"हिन्दी में देखें"}</button>{links.map(i=>{const Icon=i.icon;return <Link key={i.name} href={withLanguage(i.href)} onClick={()=>setOpen(false)} className={`flex items-center gap-3 rounded-xl px-4 py-3 ${active(i.href)?"bg-slate-900 text-cyan-400":"text-gray-300"}`}><Icon size={18}/>{i.name}</Link>})}</div></div>}
 </header>;
}
