export const dynamic = "force-dynamic";
export const revalidate = 0;

import Link from "next/link";
import { currentAffairsSourceLabel, loadCurrentAffairsArticles } from "@/lib/articleStreams";
import { createCategorySlug } from "@/lib/categoryRouting";
import { resolveCardImage } from "@/lib/news/categoryImage";
import { cleanPublicExcerpt, normalizedPaper, normalizedPublicCategory, repairedCaTitle } from "@/lib/publicArticleRepair";
import { SITE_URL } from "@/lib/siteUrl";
import { EXAM_VERTICALS, getExamVertical } from "@/lib/examPrep/sourceRegistry";

export async function generateMetadata({ searchParams }) { const params=await searchParams;const page=Math.max(1,Number(params?.page)||1);const todayOnly=params?.view==="today";const hi=params?.lang==="hi";const exam=getExamVertical(params?.exam||"upsc");const query=new URLSearchParams();if(exam.slug!=="upsc")query.set("exam",exam.slug);if(page>1)query.set("page",String(page));if(hi)query.set("lang","hi");const canonical=`${SITE_URL}/current-affairs${query.toString()?`?${query.toString()}`:""}`;const baseTitle=hi?exam.hiTitle:exam.title;const title=page<=1?baseTitle:`${baseTitle} - Page ${page}`;const description=hi?exam.hiDescription:exam.description;return{title,description,alternates:{canonical},robots:todayOnly?{index:false,follow:true}:{index:true,follow:true},openGraph:{title,description,url:canonical,type:"website"}};}
function pageHref(page,todayOnly,exam="upsc",hi=false){const p=new URLSearchParams();if(page>1)p.set("page",String(page));if(todayOnly)p.set("view","today");if(exam!=="upsc")p.set("exam",exam);if(hi)p.set("lang","hi");return p.toString()?`/current-affairs?${p}`:"/current-affairs";}
function dateLabel(value){if(!value)return"";return new Date(value).toLocaleDateString("en-IN",{timeZone:"Asia/Kolkata",day:"numeric",month:"short",year:"numeric"});}
export default async function CurrentAffairsPage({searchParams}){const params=await searchParams;const requestedPage=Math.max(1,Number(params?.page)||1);const todayOnly=params?.view==="today";const hi=params?.lang==="hi";const exam=getExamVertical(params?.exam||"upsc");const pageSize=24;const offset=(requestedPage-1)*pageSize;const{articles,total,hasMore,date,error}=await loadCurrentAffairsArticles({limit:pageSize,offset,todayOnly,exam:exam.slug,language:hi?"hi":"en"});if(error)console.error("Current affairs error:",error);const totalPages=Number.isFinite(total)?Math.max(1,Math.ceil(total/pageSize)):null;const articleSuffix=hi?"?lang=hi":"";const lead=articles?.[0];const rest=articles?.slice(1)||[];const leadImage=lead?resolveCardImage(lead):"";const leadTitle=lead?repairedCaTitle(lead):"";const leadCategory=lead?normalizedPublicCategory(lead.category,`${leadTitle} ${lead.why_news||""}`):"";
return <main className="ca-edition min-h-screen"><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 sm:py-12"><header className="ca-edition-head"><div><p className="ca-edition-kicker">CURRENT PULSE · EXAM INTELLIGENCE</p><h1>{hi?exam.hiTitle:exam.title}</h1><p className="ca-edition-deck">{hi?exam.hiDescription:exam.description}</p></div><div className="ca-edition-stamp"><strong>{date}</strong><span>{Number.isFinite(total)?total:"CURATED"} BRIEFS</span></div></header><div className="ca-exam-strip">{Object.values(EXAM_VERTICALS).map(item=><Link key={item.slug} href={pageHref(1,false,item.slug,hi)} className={exam.slug===item.slug?"is-active":""}>{item.label}</Link>)}</div><div className="ca-toolbar"><div><Link href={pageHref(1,false,exam.slug,hi)} className={!todayOnly?"is-active":""}>Archive</Link><Link href={pageHref(1,true,exam.slug,hi)} className={todayOnly?"is-active":""}>Today</Link><Link href={hi?"/categories?lang=hi":"/categories"}>Syllabus Index</Link></div><span>Page {requestedPage}{totalPages?` / ${totalPages}`:""}</span></div>
{lead?<><section className="ca-lead-story"><div className="ca-lead-copy"><div className="ca-story-meta"><span>{leadCategory||"Current Affairs"}</span><b>{normalizedPaper(lead.paper||"General Studies")}</b><time>{dateLabel(lead.created_at)}</time></div><Link href={`/current-affairs/${lead.slug}${articleSuffix}`}><h2>{leadTitle}</h2></Link><p>{cleanPublicExcerpt(lead.why_news||lead.content,leadTitle,leadImage?430:300)||"Open the brief for complete exam-oriented analysis."}</p><div className="ca-lead-footer"><small>{currentAffairsSourceLabel(lead)}</small><Link href={`/current-affairs/${lead.slug}${articleSuffix}`}>Study this brief →</Link></div></div><Link className="ca-lead-image" href={`/current-affairs/${lead.slug}${articleSuffix}`}><img src={leadImage} alt={leadTitle}/></Link></section><div className="ca-section-rule"><span>MORE CURRENT AFFAIRS</span></div><section className="ca-editorial-grid">{rest.map(article=>{const image=resolveCardImage(article);const href=`/current-affairs/${article.slug}${articleSuffix}`;const title=repairedCaTitle(article);const category=normalizedPublicCategory(article.category,`${title} ${article.why_news||""}`);return <article key={article.id} className="ca-editorial-card"><Link href={href} className="ca-editorial-image"><img src={image} alt={title} loading="lazy"/></Link><div className="ca-editorial-body"><div className="ca-story-meta"><Link href={`/category/${createCategorySlug(category)}${articleSuffix}`}>{category||"Current Affairs"}</Link><b>{normalizedPaper(article.paper||"GS")}</b><time>{dateLabel(article.created_at)}</time></div><Link href={href}><h2>{title}</h2></Link><p>{cleanPublicExcerpt(article.why_news||article.content,title,260)||"Read the complete current affairs analysis."}</p><div className="ca-card-foot"><small>{currentAffairsSourceLabel(article)}</small><Link href={href}>Open brief →</Link></div></div></article>})}</section></>:<div className="ca-empty"><h2>No current affairs briefs found</h2><p>Published administrator briefs will appear here.</p></div>}{(requestedPage>1||hasMore)&&<nav className="ca-pagination">{requestedPage>1&&<Link href={pageHref(requestedPage-1,todayOnly,exam.slug,hi)}>← Newer briefs</Link>}<strong>Page {requestedPage}{totalPages?` of ${totalPages}`:""}</strong>{hasMore&&<Link href={pageHref(requestedPage+1,todayOnly,exam.slug,hi)}>Older briefs →</Link>}</nav>}</div></main>}
