"use client";

import { useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

const MODES = [["Explain Topic","📖","Explain"],["Mains Answer","✍️","Mains"],["Prelims Facts","🎯","Prelims"],["MCQs","❓","MCQs"]];

export default function AIPage(){
  const[question,setQuestion]=useState("");const[answer,setAnswer]=useState("");const[mode,setMode]=useState("Explain Topic");const[loading,setLoading]=useState(false);const[provider,setProvider]=useState("");const[zeroAi,setZeroAi]=useState(false);const[sources,setSources]=useState([]);
  useEffect(()=>{const topic=new URLSearchParams(window.location.search).get("topic");if(!topic)return;setQuestion(`Explain ${topic}.`);},[]);
  async function askAI(){const q=question.trim();if(!q||loading)return;setLoading(true);setAnswer("");setSources([]);setProvider("");setZeroAi(false);try{const res=await fetch("/api/ask-ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:q,mode})});const data=await res.json().catch(()=>({}));if(!res.ok&&!data.answer)throw new Error(data.error||`Request failed (${res.status}).`);setAnswer(data.answer||"No answer was generated.");setSources(Array.isArray(data.sources)?data.sources:[]);setProvider(data.provider||"");setZeroAi(Boolean(data.zeroAi));}catch(err){setAnswer(err?.message||"Something went wrong. Please try again.");}finally{setLoading(false);}}
  return <main className="min-h-screen bg-slate-950 text-white"><div className="mx-auto max-w-5xl px-4 py-10 sm:px-6 sm:py-14">
    <header className="rounded-3xl border border-cyan-400/20 bg-gradient-to-br from-slate-900 via-slate-900 to-cyan-950/30 p-6 shadow-2xl shadow-black/20 sm:p-9"><div className="inline-flex rounded-full border border-cyan-400/30 bg-cyan-400/10 px-3 py-1 text-xs font-black uppercase tracking-[.18em] text-cyan-300">Quota-first evidence assistant</div><h1 className="mt-4 text-4xl font-black tracking-tight sm:text-5xl">Ask CurrentPulse <span className="text-cyan-300">AI</span></h1><p className="mt-4 max-w-3xl text-base leading-7 text-slate-300 sm:text-lg">Clear answers from CurrentPulse and free reference sources, with clean facts, context and source links instead of raw article dumps.</p></header>
    <section className="mt-6 rounded-3xl border border-slate-800 bg-slate-900/90 p-5 shadow-xl shadow-black/20 sm:p-7"><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{MODES.map(([value,icon,label])=><button key={value} type="button" onClick={()=>setMode(value)} className={`rounded-xl border px-3 py-3 text-sm font-black transition ${mode===value?"border-cyan-300 bg-cyan-300 text-slate-950":"border-slate-700 bg-slate-950 text-slate-200 hover:border-cyan-400/60"}`}><span className="mr-1.5">{icon}</span>{label}</button>)}</div>
    <label className="mt-6 block text-sm font-black text-slate-200" htmlFor="ai-question">Your question</label><textarea id="ai-question" value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==="Enter")askAI();}} placeholder="Example: What changed in RBI monetary policy and what should I remember for Prelims?" rows={5} className="mt-2 block w-full resize-y rounded-2xl border border-slate-700 bg-slate-950 px-4 py-4 text-base leading-7 text-white outline-none placeholder:text-slate-600 focus:border-cyan-400 focus:ring-2 focus:ring-cyan-400/20"/>
    <div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-2xl text-xs leading-5 text-slate-500">Current topics use published CurrentPulse evidence first. Stable topics can use free reference sources.</p><button type="button" onClick={askAI} disabled={loading||!question.trim()} className="rounded-xl bg-cyan-300 px-5 py-3 text-sm font-black text-slate-950 disabled:cursor-not-allowed disabled:opacity-40">{loading?"Retrieving evidence…":"Ask CurrentPulse AI →"}</button></div></section>
    {loading&&<div className="mt-6 rounded-2xl border border-cyan-400/20 bg-cyan-400/5 p-5 text-cyan-100"><strong>Checking free sources first…</strong><p className="mt-1 text-sm text-slate-400">Retrieving the smallest relevant evidence set.</p></div>}
    {answer&&!loading&&<section className="mt-6 rounded-3xl border border-slate-800 bg-slate-900 p-6 sm:p-8"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 pb-4"><div><small className="font-black uppercase tracking-wider text-cyan-300">{zeroAi?"Zero-AI source response":"Evidence-backed reasoning"}</small><h2 className="mt-1 text-2xl font-black">Answer</h2></div>{provider&&<span className="rounded-full bg-slate-800 px-3 py-1 text-xs font-bold text-slate-300">{provider}</span>}</div><div className="article-rich-content mt-6 max-w-none space-y-4 text-[15px] leading-7 text-slate-200 [&_h3]:mt-7 [&_h3]:text-lg [&_h3]:font-black [&_h3]:text-cyan-200 [&_li]:my-1.5 [&_strong]:text-white"><ReactMarkdown remarkPlugins={[remarkGfm]}>{answer}</ReactMarkdown></div>{sources.length>0&&<div className="mt-6 border-t border-slate-800 pt-5"><strong className="text-sm">Sources</strong><div className="mt-3 flex flex-wrap gap-2">{sources.slice(0,3).map(source=><a key={source.url} href={source.url} target="_blank" rel="noopener noreferrer" className="rounded-xl border border-slate-700 bg-slate-950/70 px-4 py-3 text-sm font-bold text-cyan-300 hover:border-cyan-400">{source.title}</a>)}</div></div>}</section>}
  </div></main>;
}
