"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {createMemberBrowserClient} from "@/lib/supabase/browser";
type Product={id:string;name:string;product_type:string;test_credits:number;price_paise:number};
declare global{interface Window{Razorpay:any}}
function loadRazorpay(){return new Promise<boolean>(resolve=>{if(window.Razorpay)return resolve(true);const s=document.createElement("script");s.src="https://checkout.razorpay.com/v1/checkout.js";s.onload=()=>resolve(true);s.onerror=()=>resolve(false);document.body.appendChild(s)})}
export default function Shop(){const [products,setProducts]=useState<Product[]>([]),[email,setEmail]=useState<string|null>(null),[busy,setBusy]=useState<string|null>(null),[msg,setMsg]=useState(""),[paymentsReady,setPaymentsReady]=useState(false),[readyChecked,setReadyChecked]=useState(false);
 useEffect(()=>{(async()=>{const s=createMemberBrowserClient();const [{data:{user}},{data},config]=await Promise.all([s.auth.getUser(),s.from("mains_products").select("id,name,product_type,test_credits,price_paise").eq("active",true).order("price_paise"),fetch("/api/payments/config",{cache:"no-store"}).then(r=>r.ok?r.json():({enabled:false})).catch(()=>({enabled:false}))]);setEmail(user?.email||null);setProducts((data||[]) as Product[]);setPaymentsReady(config.enabled===true);setReadyChecked(true)})()},[]);
 async function buy(p:Product){if(!paymentsReady){setMsg("Online checkout is not active yet. Your account and products are ready; no payment will be collected until the payment gateway is configured.");return;}setBusy(p.id);setMsg("");try{const s=createMemberBrowserClient();const {data:{session}}=await s.auth.getSession();if(!session)throw new Error("Please sign in first.");const r=await fetch("/api/payments/razorpay/order",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({productId:p.id})});const o=await r.json();if(!r.ok)throw new Error(o.error||"Payment could not start");if(!await loadRazorpay())throw new Error("Secure checkout could not load");new window.Razorpay({key:o.keyId,amount:o.amount,currency:o.currency,name:"CurrentPulse AI",description:o.name,order_id:o.orderId,prefill:{email:o.email},theme:{color:"#34d399"},handler:async(resp:any)=>{const v=await fetch("/api/payments/razorpay/verify",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(resp)});const out=await v.json();if(!v.ok){setMsg(out.error||"Payment verification failed. Contact support; do not pay again.");return;}setMsg("Payment verified. Your purchase is now attached to your CurrentPulse account.");setTimeout(()=>location.href="/member",1000)}}).open();}catch(e){setMsg(e instanceof Error?e.message:"Payment failed")}finally{setBusy(null)}}
 return <main className="min-h-screen bg-[#07111f] px-5 py-14 text-white"><div className="mx-auto max-w-6xl"><Link href="/member" className="font-bold text-emerald-300">← My dashboard</Link><div className="mt-5 text-xs font-black uppercase tracking-[.18em] text-amber-300">Secure CurrentPulse Shop</div><h1 className="mt-2 text-4xl font-black">Tests, packages & digital resources</h1><p className="mt-3 max-w-3xl text-slate-400">Prices come from the server database. Test credits unlock only after server-side payment verification.</p>{readyChecked&&!paymentsReady&&<div className="mt-6 rounded-xl border border-amber-300/25 bg-amber-300/10 p-4 text-amber-100"><strong>Checkout setup in progress.</strong> Products and member accounts are available, but online payment is intentionally disabled until a verified payment gateway is connected. No money can be collected accidentally.</div>}{!email&&<div className="mt-6 rounded-xl bg-cyan-300/10 p-4 text-cyan-100">You can <Link className="font-black underline" href="/member/login">sign in or create your account</Link> now. Purchases will open after checkout setup is complete.</div>}{msg&&<div className="mt-6 rounded-xl border border-cyan-400/30 bg-cyan-400/10 p-4 text-cyan-100">{msg}</div>}<div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{products.map(p=><div key={p.id} className="rounded-2xl border border-slate-700 bg-slate-900 p-6"><div className="text-xs font-bold uppercase tracking-wider text-slate-500">{p.product_type.replaceAll("_"," ")}</div><h2 className="mt-2 text-xl font-black">{p.name}</h2><div className="mt-4 text-3xl font-black text-emerald-300">₹{(p.price_paise/100).toFixed(0)}</div><div className="mt-1 text-sm text-slate-400">{p.test_credits?`${p.test_credits} test credit${p.test_credits>1?"s":""}`:"Digital resource"}</div><button disabled={!email||!paymentsReady||busy===p.id} onClick={()=>buy(p)} className="mt-5 w-full rounded-xl bg-emerald-300 px-4 py-3 font-black text-slate-950 disabled:cursor-not-allowed disabled:opacity-40">{!readyChecked?"Checking checkout…":!paymentsReady?"Checkout coming soon":busy===p.id?"Starting checkout…":"Buy securely"}</button></div>)}</div></div></main>}
