export const UPSC_FOUNDATION_FALLBACK = [
  {
    id: "foundation-money-bill",
    type: "Polity · Moderate",
    prompt: "With reference to a Money Bill in the Indian Parliament, consider the following statements:\n\n1. It can be introduced only in the Lok Sabha.\n2. The Speaker's decision on whether a Bill is a Money Bill is final.\n3. The Rajya Sabha must return it with recommendations within fourteen days.\n\nWhich of the statements given above are correct?",
    options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2 and 3"],
    answer: "1, 2 and 3",
    explanation: "All three statements follow Article 110 and the special procedure in Article 109. A Money Bill originates only in the Lok Sabha; the Speaker certifies it; and the Rajya Sabha may recommend changes but must return it within fourteen days.",
    difficulty: "Moderate",
    category: "Polity & Governance",
    articleUrl: "/category/polity",
    articleTitle: "Revise Polity current affairs",
  },
  {
    id: "foundation-sdr",
    type: "Economy · Moderate",
    prompt: "With reference to Special Drawing Rights (SDRs), consider the following statements:\n\n1. The SDR is an international reserve asset created by the International Monetary Fund.\n2. It is a currency that individuals may use for ordinary commercial payments.\n3. Its value is based on a basket of major currencies.\n\nWhich of the statements given above are correct?",
    options: ["1 only", "1 and 3 only", "2 and 3 only", "1, 2 and 3"],
    answer: "1 and 3 only",
    explanation: "Statements 1 and 3 are correct. The IMF created the SDR as a supplementary reserve asset and values it using a currency basket. It is not a currency for retail transactions, so statement 2 is incorrect.",
    difficulty: "Moderate",
    category: "Economy",
    articleUrl: "/category/economy",
    articleTitle: "Revise Economy current affairs",
  },
  {
    id: "foundation-ramsar",
    type: "Environment · Moderate",
    prompt: "With reference to the Ramsar Convention, consider the following statements:\n\n1. The Montreux Record lists Ramsar sites where changes in ecological character have occurred, are occurring or are likely to occur.\n2. Every Ramsar site must also be notified as a National Park under Indian law.\n3. The Convention promotes the wise use of wetlands.\n\nWhich of the statements given above are correct?",
    options: ["1 and 2 only", "2 only", "1 and 3 only", "1, 2 and 3"],
    answer: "1 and 3 only",
    explanation: "Statements 1 and 3 are correct. The Montreux Record flags ecological change, and wise use is central to the Convention. Ramsar designation does not itself require National Park status, making statement 2 incorrect.",
    difficulty: "Moderate",
    category: "Environment",
    articleUrl: "/category/environment",
    articleTitle: "Revise Environment current affairs",
  },
  {
    id: "foundation-crispr",
    type: "Science & Technology · Moderate",
    prompt: "Regarding CRISPR-Cas9 gene editing, consider the following statements:\n\n1. A guide RNA helps identify the target DNA sequence.\n2. Cas9 can create a cut in DNA at the targeted location.\n3. The technique can be applied only to plant cells.\n\nWhich of the statements given above are correct?",
    options: ["1 only", "1 and 2 only", "2 and 3 only", "1, 2 and 3"],
    answer: "1 and 2 only",
    explanation: "Statements 1 and 2 describe the guide-and-cut mechanism of CRISPR-Cas9. The platform is studied and used across many kinds of organisms and cells, so the plant-only claim in statement 3 is incorrect.",
    difficulty: "Moderate",
    category: "Science & Technology",
    articleUrl: "/category/science-tech",
    articleTitle: "Revise Science & Technology current affairs",
  },
  {
    id: "foundation-eez",
    type: "Geography · Difficult",
    prompt: "With reference to the Exclusive Economic Zone (EEZ) under the United Nations Convention on the Law of the Sea, consider the following statements:\n\n1. It may extend up to 200 nautical miles from the baselines.\n2. A coastal State exercises the same complete sovereignty over the EEZ as it does over its territorial sea.\n3. The coastal State has sovereign rights for exploring and exploiting natural resources in the EEZ.\n\nWhich of the statements given above are correct?",
    options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2 and 3"],
    answer: "1 and 3 only",
    explanation: "Statements 1 and 3 are correct. An EEZ can extend to 200 nautical miles, and the coastal State has specified sovereign rights over resources. That is not identical to full sovereignty over the territorial sea, so statement 2 is incorrect.",
    difficulty: "Difficult",
    category: "Geography",
    articleUrl: "/category/geography",
    articleTitle: "Revise Geography current affairs",
  },
  {
    id: "foundation-liquidity",
    type: "Economy · Moderate",
    prompt: "Consider the following statements about monetary-policy instruments in India:\n\n1. The repo rate is the rate at which the Reserve Bank of India lends short-term funds to banks against eligible collateral.\n2. An increase in the Cash Reserve Ratio directly increases the lendable resources of banks.\n3. A sale of government securities by the Reserve Bank of India through open-market operations generally absorbs liquidity.\n\nWhich of the statements given above are correct?",
    options: ["1 only", "1 and 3 only", "2 and 3 only", "1, 2 and 3"],
    answer: "1 and 3 only",
    explanation: "Statements 1 and 3 are correct. Repo is a collateralised liquidity facility, while an RBI sale of securities absorbs funds. A higher Cash Reserve Ratio locks a larger share of deposits with the RBI and therefore reduces, rather than increases, banks' lendable resources.",
    difficulty: "Moderate",
    category: "Economy",
    articleUrl: "/category/economy",
    articleTitle: "Revise Economy current affairs",
  },
  {
    id: "foundation-finance-commission",
    type: "Polity · Moderate",
    prompt: "With reference to the Finance Commission of India, consider the following statements:\n\n1. It is constituted by the President under Article 280 of the Constitution.\n2. It recommends the distribution of the net proceeds of taxes between the Union and the States.\n3. It is a permanent constitutional body with a fixed secretariat.\n\nWhich of the statements given above are correct?",
    options: ["1 only", "1 and 2 only", "2 and 3 only", "1, 2 and 3"],
    answer: "1 and 2 only",
    explanation: "Statements 1 and 2 are correct. Article 280 provides for periodic constitution of a Finance Commission by the President and assigns it tax-devolution and related fiscal recommendations. It is constituted periodically, not as a permanent body, so statement 3 is incorrect.",
    difficulty: "Moderate",
    category: "Polity & Governance",
    articleUrl: "/category/polity",
    articleTitle: "Revise Polity current affairs",
  },
  {
    id: "foundation-mpc",
    type: "Economy · Difficult",
    prompt: "Regarding the Monetary Policy Committee (MPC) in India, consider the following statements:\n\n1. It has six members.\n2. The Governor of the Reserve Bank of India is its ex officio Chairperson.\n3. In the event of a tie, the Governor has a casting vote.\n\nWhich of the statements given above are correct?",
    options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2 and 3"],
    answer: "1, 2 and 3",
    explanation: "All three statements are correct. The MPC consists of three RBI representatives and three members appointed by the Central Government. The RBI Governor chairs it and exercises a second or casting vote when votes are equally divided.",
    difficulty: "Difficult",
    category: "Economy",
    articleUrl: "/category/economy",
    articleTitle: "Revise Economy current affairs",
  },
  {
    id: "foundation-hotspots",
    type: "Environment · Moderate",
    prompt: "With reference to biodiversity hotspots, consider the following statements:\n\n1. High endemism is one of the criteria used to identify a biodiversity hotspot.\n2. Significant loss of original natural vegetation is also part of the identification criteria.\n3. Every biodiversity hotspot is legally designated as a protected area under Indian law.\n\nWhich of the statements given above are correct?",
    options: ["1 and 2 only", "2 only", "1 and 3 only", "1, 2 and 3"],
    answer: "1 and 2 only",
    explanation: "Statements 1 and 2 are correct: the hotspot concept combines exceptional plant endemism with extensive habitat loss. A hotspot is a conservation-priority classification, not by itself a statutory protected-area category, so statement 3 is incorrect.",
    difficulty: "Moderate",
    category: "Environment",
    articleUrl: "/category/environment",
    articleTitle: "Revise Environment current affairs",
  },
  {
    id: "foundation-defection",
    type: "Polity · Difficult",
    prompt: "With reference to the Tenth Schedule of the Constitution, consider the following statements:\n\n1. Questions of disqualification on the ground of defection are decided by the presiding officer of the House.\n2. The merger exception requires support from at least two-thirds of the members of the legislature party concerned.\n3. A nominated member can join a political party at any time during the term without attracting the Schedule.\n\nWhich of the statements given above are correct?",
    options: ["1 only", "1 and 2 only", "2 and 3 only", "1, 2 and 3"],
    answer: "1 and 2 only",
    explanation: "Statements 1 and 2 are correct. The presiding officer decides disqualification petitions, subject to judicial review, and the merger protection uses a two-thirds threshold. A nominated member may join a party within six months of taking the seat; joining later can attract disqualification, so statement 3 is incorrect.",
    difficulty: "Difficult",
    category: "Polity & Governance",
    articleUrl: "/category/polity",
    articleTitle: "Revise Polity current affairs",
  },
];

export function mapStoredQuiz(rows = []) {
  return rows
    .filter(
      (row) =>
        row?.prompt &&
        Array.isArray(row.options) &&
        row.options.length === 4 &&
        Number.isInteger(row.correct_index) &&
        row.correct_index >= 0 &&
        row.correct_index <= 3
    )
    .map((row) => ({
      id: `daily-${row.id}`,
      type: `${row.category || "Current Affairs"} · ${row.difficulty || "Moderate"}`,
      prompt: row.prompt,
      options: row.options,
      answer: row.options[row.correct_index],
      explanation: row.explanation,
      difficulty: row.difficulty,
      category: row.category,
      quizDate: row.quiz_date,
      articleUrl: row.source_slug ? `/current-affairs/${row.source_slug}` : "/current-affairs",
      articleTitle: row.source_title || "Source current-affairs analysis",
    }));
}
