export const PYQ_ITEMS = [
  {
    year: 2023,
    paper: "GS-2",
    topic: "Polity & Governance",
    question: "Examine why constitutionally protected judicial independence is essential for a democracy.",
    approach: ["Define judicial independence", "Explain constitutional safeguards", "Discuss accountability without executive interference", "Conclude with reform priorities"],
  },
  {
    year: 2023,
    paper: "GS-3",
    topic: "Economy",
    question: "Assess the progress of digitalisation in the Indian economy and the challenges it continues to face.",
    approach: ["Use adoption and inclusion dimensions", "Cover infrastructure and skills", "Discuss privacy and cyber risks", "Suggest inclusive digital public infrastructure"],
  },
  {
    year: 2022,
    paper: "GS-2",
    topic: "Polity & Governance",
    question: "Discuss the role of the Election Commission in the evolution and enforcement of the Model Code of Conduct.",
    approach: ["State constitutional mandate", "Trace MCC development", "Evaluate enforcement limitations", "Suggest legal and institutional strengthening"],
  },
  {
    year: 2022,
    paper: "GS-3",
    topic: "Environment",
    question: "Explain India’s renewable-energy transition and the constraints affecting its pace and reliability.",
    approach: ["Present the energy-transition context", "Cover solar, wind and storage", "Discuss grid and finance constraints", "Link to climate and energy security"],
  },
  {
    year: 2021,
    paper: "GS-2",
    topic: "Polity & Governance",
    question: "Evaluate how pressure groups influence public policy in India and distinguish them from political parties.",
    approach: ["Define both institutions", "Compare objectives and methods", "Use policy examples", "Balance participation with transparency concerns"],
  },
  {
    year: 2021,
    paper: "GS-3",
    topic: "Defence & Security",
    question: "Analyse the major internal-security challenges created by cross-border cyber threats and online radicalisation.",
    approach: ["Classify threat vectors", "Explain state and non-state roles", "Assess coordination gaps", "Propose legal, technical and social responses"],
  },
  {
    year: 2020,
    paper: "GS-2",
    topic: "Social Issues",
    question: "Assess how local institutions can improve the delivery of health, education and welfare services.",
    approach: ["Connect decentralisation with service delivery", "Discuss funds, functions and functionaries", "Use local innovations", "Recommend capacity and accountability reforms"],
  },
  {
    year: 2020,
    paper: "GS-3",
    topic: "Economy",
    question: "Discuss the role of infrastructure investment in sustaining inclusive economic growth in India.",
    approach: ["Explain the growth multiplier", "Cover physical and social infrastructure", "Discuss financing and implementation", "Link infrastructure to jobs and regional balance"],
  },
  {
    year: 2019,
    paper: "GS-2",
    topic: "Polity & Governance",
    question: "Examine the reasons for declining legislative scrutiny and suggest measures to strengthen Parliament’s deliberative role.",
    approach: ["Use sitting and committee dimensions", "Explain political and procedural causes", "Assess democratic impact", "Recommend committee and calendar reforms"],
  },
  {
    year: 2019,
    paper: "GS-3",
    topic: "Environment",
    question: "Why is India experiencing severe water stress despite receiving substantial rainfall? Discuss appropriate responses.",
    approach: ["Separate availability from access", "Cover groundwater and spatial variation", "Discuss demand and governance", "Propose watershed and pricing reforms"],
  },
  {
    year: 2018,
    paper: "GS-2",
    topic: "Polity & Governance",
    question: "Evaluate the contribution of the Comptroller and Auditor General to legislative accountability.",
    approach: ["State constitutional position", "Explain audit types and reporting", "Assess PAC linkage", "Discuss independence and follow-up gaps"],
  },
  {
    year: 2018,
    paper: "GS-3",
    topic: "Science & Technology",
    question: "Discuss how science and technology can improve development outcomes while creating new ethical and regulatory challenges.",
    approach: ["Use sectoral applications", "Explain inclusion benefits", "Identify safety, privacy and equity risks", "Recommend adaptive regulation"],
  },
];
