-- Manual Admin and strict-PDF records are immutable to automated maintenance.
alter table public.articles
  add column if not exists manual_protected boolean not null default false;

create index if not exists articles_manual_protected_status_idx
  on public.articles (manual_protected, status);

-- Preserve the exact recovered PDF rows and all existing Admin PDF imports.
update public.articles
set manual_protected = true
where id in (3648, 3649, 3650)
   or exists (
     select 1 from public.article_sources s
     where s.article_id = articles.id
       and s.source_name in ('CurrentPulse Admin CA PDF', 'CurrentPulse Admin News PDF')
   );

-- Restore the original rows only; no replacement rows are inserted.
update public.articles
set status = 'published'
where id in (3648, 3649, 3650)
  and manual_protected = true;

-- Durable, queryable history for every subsequent mutation of protected rows.
create table if not exists public.article_mutation_audit (
  id bigint generated by default as identity primary key,
  article_id bigint not null,
  operation text not null,
  occurred_at timestamptz not null default now(),
  actor text not null default current_user,
  old_row jsonb,
  new_row jsonb
);
alter table public.article_mutation_audit enable row level security;
revoke all on public.article_mutation_audit from public, anon, authenticated;

create or replace function public.audit_manual_article_mutation()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if (tg_op = 'DELETE' and old.manual_protected)
     or (tg_op <> 'DELETE' and (old.manual_protected or new.manual_protected)) then
    insert into public.article_mutation_audit(article_id, operation, old_row, new_row)
    values (coalesce(new.id, old.id), tg_op, to_jsonb(old), case when tg_op = 'DELETE' then null else to_jsonb(new) end);
  end if;
  return coalesce(new, old);
end;
$$;
revoke all on function public.audit_manual_article_mutation() from public, anon, authenticated;
drop trigger if exists audit_manual_article_mutation on public.articles;
create trigger audit_manual_article_mutation
after insert or update or delete on public.articles
for each row execute function public.audit_manual_article_mutation();
