-- ResultPulse AI + notification foundation.
-- Safe to run repeatedly: all objects use IF NOT EXISTS where PostgreSQL permits.
create extension if not exists pgcrypto;

create table if not exists public.exam_updates (
  id bigint generated by default as identity primary key,
  fingerprint text not null unique,
  slug text not null unique,
  title text not null,
  exam_name text,
  agency text,
  update_type text not null default 'notification',
  summary text,
  official_url text not null,
  source_name text,
  source_group text,
  source_url text,
  source_published_at timestamptz,
  deadline_at timestamptz,
  exam_date timestamptz,
  important_dates jsonb not null default '[]'::jsonb,
  tags text[] not null default '{}'::text[],
  status text not null default 'published',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.exam_updates add column if not exists source_group text;
create index if not exists exam_updates_status_created_idx on public.exam_updates(status, created_at desc);
create index if not exists exam_updates_type_created_idx on public.exam_updates(update_type, created_at desc);
create index if not exists exam_updates_source_published_idx on public.exam_updates(source_published_at desc);
create index if not exists exam_updates_source_group_idx on public.exam_updates(source_group, created_at desc);
create index if not exists exam_updates_exam_name_idx on public.exam_updates(exam_name);

alter table public.exam_updates enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='exam_updates' and policyname='Public can read published exam updates') then
    create policy "Public can read published exam updates" on public.exam_updates for select using (status = 'published');
  end if;
end $$;

grant select on public.exam_updates to anon, authenticated;

create table if not exists public.notification_subscriptions (
  id uuid primary key default gen_random_uuid(),
  email text,
  phone_e164 text,
  email_enabled boolean not null default true,
  whatsapp_enabled boolean not null default false,
  topics text[] not null default '{}'::text[],
  status text not null default 'active',
  consent_at timestamptz not null default now(),
  unsubscribe_token uuid not null default gen_random_uuid() unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint notification_contact_present check (email is not null or phone_e164 is not null)
);
create unique index if not exists notification_email_unique on public.notification_subscriptions(lower(email)) where email is not null;
create unique index if not exists notification_phone_unique on public.notification_subscriptions(phone_e164) where phone_e164 is not null;
create index if not exists notification_subscriptions_status_idx on public.notification_subscriptions(status);
create index if not exists notification_subscriptions_status_created_idx on public.notification_subscriptions(status, created_at asc);

alter table public.notification_subscriptions enable row level security;
revoke all on public.notification_subscriptions from anon, authenticated;

create table if not exists public.notification_events (
  id bigint generated by default as identity primary key,
  entity_key text not null unique,
  topic text not null,
  title text not null,
  summary text,
  url text not null,
  status text not null default 'pending',
  delivery_offset integer not null default 0,
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.notification_events add column if not exists delivery_offset integer not null default 0;
create index if not exists notification_events_pending_idx on public.notification_events(status, created_at asc);
alter table public.notification_events enable row level security;
revoke all on public.notification_events from anon, authenticated;

create table if not exists public.notification_deliveries (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.notification_events(id) on delete cascade,
  subscription_id uuid not null references public.notification_subscriptions(id) on delete cascade,
  channel text not null,
  status text not null default 'processing',
  error text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  unique(event_id, subscription_id, channel)
);
create index if not exists notification_deliveries_status_idx on public.notification_deliveries(status, created_at asc);
alter table public.notification_deliveries enable row level security;
revoke all on public.notification_deliveries from anon, authenticated;

-- Hot CurrentPulse reader-path indexes. These are also safe if a previous
-- migration already created them.
create index if not exists articles_status_created_at_idx on public.articles(status, created_at desc);
create index if not exists article_sources_kind_article_idx on public.article_sources(source_kind, article_id);
create index if not exists article_sources_kind_published_article_idx on public.article_sources(source_kind, source_published_at desc, article_id);
