create table if not exists public.reader_release_requests (
  id bigint generated by default as identity primary key,
  entity_key text not null,
  stream text not null check (stream in ('news', 'coverage', 'pdf', 'exam', 'quiz', 'site')),
  status text not null default 'pending' check (status in ('pending', 'completed')),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  last_error text,
  last_dispatched_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists reader_release_requests_pending_idx
  on public.reader_release_requests (status, created_at, id)
  where status = 'pending';

alter table public.reader_release_requests enable row level security;
revoke all on public.reader_release_requests from anon, authenticated;
revoke all on public.reader_release_requests from service_role;
grant select, insert, update on public.reader_release_requests to service_role;
grant usage, select on sequence public.reader_release_requests_id_seq to service_role;

create index if not exists article_queue_article_id_idx
  on public.article_queue (article_id)
  where article_id is not null;
create index if not exists articles_author_id_idx
  on public.articles (author_id)
  where author_id is not null;
create index if not exists notification_deliveries_subscription_id_idx
  on public.notification_deliveries (subscription_id);

alter function public.update_updated_at_column() set search_path = pg_catalog, public;

drop policy if exists "Users can view their own profile" on public.profiles;
create policy "Users can view their own profile" on public.profiles
  for select to authenticated
  using ((select auth.uid()) = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile" on public.profiles
  for update to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);
